import * as stylex from "@stylexjs/stylex";

export const composerDrawerStyles = stylex.create({
  root: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: "var(--borderMuted, var(--borderLight))",
    paddingBottom: "var(--space-2)",
    marginBottom: "var(--space-1)",
  },
  toggleBar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    padding: "2px 4px",
    borderRadius: "var(--radius-xs, 4px)",
    backgroundColor: "transparent",
    color: "var(--textSecondary)",
    fontSize: "var(--fontSize-xs, 12px)",
    lineHeight: 1.2,
  },
  summaryBtn: {
    display: "flex",
    alignItems: "center",
    flex: 1,
    minWidth: 0,
    background: "transparent",
    borderWidth: 0,
    borderStyle: "none",
    padding: "2px 4px",
    borderRadius: "var(--radius-xs, 4px)",
    cursor: "pointer",
    textAlign: "left",
    font: "inherit",
    color: "inherit",
    transition: "background 0.15s ease, color 0.15s ease",
    ":hover": {
      backgroundColor: "var(--surfaceInteractiveHover, var(--backgroundHover, rgba(0,0,0,0.04)))",
      color: "var(--text)",
    },
    ":focus-visible": {
      outline: "2px solid var(--primary)",
      outlineOffset: "1px",
    },
  },
  chevronBtn: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    background: "transparent",
    borderWidth: 0,
    borderStyle: "none",
    padding: "2px 4px",
    borderRadius: "var(--radius-xs, 4px)",
    cursor: "pointer",
    color: "inherit",
    transition: "background 0.15s ease, color 0.15s ease",
    ":hover": {
      backgroundColor: "var(--surfaceInteractiveHover, var(--backgroundHover, rgba(0,0,0,0.04)))",
      color: "var(--text)",
    },
    ":focus-visible": {
      outline: "2px solid var(--primary)",
      outlineOffset: "1px",
    },
  },
  summaryLeft: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    flexWrap: "nowrap",
    overflow: "hidden",
    minWidth: 0,
  },
  summaryRight: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    flexShrink: 0,
  },
  badge: {
    display: "inline-flex",
    alignItems: "center",
    gap: "4px",
    padding: "2px 6px",
    borderRadius: "999px",
    backgroundColor: "var(--surfaceInset, var(--backgroundSecondary))",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "var(--borderMuted, var(--borderLight))",
    color: "var(--textSecondary)",
    fontSize: "11px",
    fontWeight: 500,
    flexShrink: 0,
    maxWidth: "100%",
  },
  badgeIcon: {
    display: "inline-flex",
    alignItems: "center",
    color: "var(--textTertiary)",
  },
  miniProgressWrap: {
    display: "inline-flex",
    alignItems: "center",
    gap: "4px",
  },
  miniProgressTrack: {
    width: "44px",
    height: "4px",
    borderRadius: "999px",
    backgroundColor: "var(--borderMuted, var(--borderLight))",
    overflow: "hidden",
  },
  miniProgressFill: {
    height: "100%",
    borderRadius: "999px",
    backgroundColor: "var(--primary)",
    transition: "width 0.3s ease",
  },
  miniProgressText: {
    fontSize: "11px",
    fontVariantNumeric: "tabular-nums",
    color: "var(--textTertiary)",
  },
  chevron: {
    display: "inline-flex",
    alignItems: "center",
    transition: "transform 0.2s ease",
    color: "var(--textTertiary)",
  },
  chevronExpanded: {
    transform: "rotate(180deg)",
  },
  content: {
    display: "flex",
    flexDirection: "column",
    gap: "var(--space-2)",
    maxHeight: "260px",
    overflowY: "auto",
    paddingTop: "var(--space-2)",
  },
});
