import * as stylex from "@stylexjs/stylex";

/**
 * 消息输入区样式体系（message-input.css → StyleX 1:1 迁出，2026-08-30）。
 * MessageInputContainer, MessageInputCore, SendButton, VoiceInputButton,
 * CreateTaskModal, ImageConfigRow, ScrollToBottomButton, etc.
 *
 * 与原 CSS 保持 1:1：同一元素、同一声明、同值。
 * 运行时 :root 变量由 GlobalThemeController 注入，var(--global-*) 原样保留。
 */
export const messageInputStyles = stylex.create({
  /* ── ActionButton / SendButton ── */
  sendButton: {
    "--button-size": "36px",
    width: "var(--button-size)",
    height: "var(--button-size)",
    position: "relative",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "50%",
    borderWidth: 0,
    borderStyle: "none",
    outline: "none",
    padding: 0,
    transition:
      "background 0.18s ease, color 0.18s ease, border-color 0.18s ease, transform 0.18s ease, box-shadow 0.18s ease",
    cursor: "pointer",
    flexShrink: 0,
    "@media (max-width: 768px)": {
      "--button-size": "40px",
    },
  },
  sendMode: {
    backgroundColor: "var(--primary)",
    color: "var(--textOnPrimary, white)",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "var(--primaryBorder, var(--primary))",
    boxShadow:
      "0 6px 14px -12px var(--shadowMedium), inset 0 1px 0 rgba(255, 255, 255, 0.12)",
    ":hover": {
      backgroundColor: "color-mix(in srgb, var(--primary) 94%, white)",
      transform: "translateY(-1px)",
      boxShadow:
        "0 8px 18px -14px var(--shadowMedium), inset 0 1px 0 rgba(255, 255, 255, 0.18)",
    },
    ":active": {
      transform: "translateY(0)",
      boxShadow:
        "0 2px 6px -4px var(--shadowMedium), inset 0 1px 0 rgba(0, 0, 0, 0.08)",
    },
  },
  stopMode: {
    backgroundColor: "var(--surfaceInset, var(--surfaceRaised, var(--backgroundSecondary)))",
    color: "var(--danger, #f87171)",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "var(--borderMuted, var(--borderLight))",
    boxShadow: "0 1px 2px var(--shadowLight)",
    ":hover": {
      backgroundColor: "color-mix(in srgb, var(--danger, #f87171) 12%, var(--surfaceInset, var(--backgroundSecondary)))",
      borderColor: "var(--danger, #f87171)",
      transform: "translateY(-1px)",
      boxShadow: "0 6px 14px -12px var(--shadowMedium)",
    },
    ":active": {
      transform: "translateY(0)",
    },
  },
  sendButtonLoading: {
    backgroundColor: "var(--surfaceInset, var(--surfaceRaised, var(--backgroundSecondary)))",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "var(--borderMuted, var(--borderLight))",
    color: "var(--primary)",
    boxShadow: "0 1px 2px var(--shadowLight)",
    cursor: "progress",
    ":hover": {
      transform: "none",
      backgroundColor: "var(--surfaceInset, var(--surfaceRaised, var(--backgroundSecondary)))",
      borderColor: "var(--borderMuted, var(--borderLight))",
      boxShadow: "0 1px 2px var(--shadowLight)",
    },
    ":active": {
      transform: "none",
      backgroundColor: "var(--surfaceInset, var(--surfaceRaised, var(--backgroundSecondary)))",
    },
  },
  sendButtonDisabled: {
    opacity: 0.4,
    cursor: "not-allowed",
    filter: "grayscale(0.2) saturate(0.8)",
    pointerEvents: "none",
  },
  sendIcon: {
    transition:
      "transform 0.22s cubic-bezier(0.25, 0.46, 0.45, 0.94), opacity 0.22s ease",
    transform: "none",
  },
  sendIconAnimating: {
    animationName: "sendArrowUp",
    animationDuration: "0.45s",
    animationTimingFunction: "cubic-bezier(0.25, 0.46, 0.45, 0.94)",
    animationFillMode: "forwards",
  },
  stopIndicator: {
    width: "14px",
    height: "14px",
    backgroundColor: "currentColor",
    borderRadius: "var(--radius-xs)",
    transition: "all 0.28s cubic-bezier(0.25, 0.46, 0.45, 0.94)",
    opacity: 0.8,
  },
  sendLoadingIcon: {
    width: "20px",
    height: "20px",
    display: "block",
    transformOrigin: "50% 50%",
    animationName: "message-input-spin",
    animationDuration: "0.9s",
    animationTimingFunction: "linear",
    animationIterationCount: "infinite",
    willChange: "transform",
  },

  /* ── StopGenerationButton ── */
  stopGenerationBtn: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "6px",
    padding: "6px 14px",
    borderRadius: "var(--radius-md)",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "var(--borderMuted, var(--borderLight))",
    backgroundColor: "var(--surfaceRaised, var(--backgroundSecondary))",
    color: "var(--textSecondary)",
    fontSize: "var(--fontSize-sm)",
    fontWeight: 500,
    cursor: "pointer",
    boxShadow: "0 1px 2px var(--shadowLight)",
    transition:
      "background 0.15s ease, border-color 0.15s ease, color 0.15s ease, transform 0.15s ease, box-shadow 0.15s ease",
    ":hover": {
      backgroundColor: "color-mix(in srgb, var(--danger, #f87171) 10%, var(--surfaceRaised, var(--backgroundSecondary)))",
      borderColor: "var(--danger, #f87171)",
      color: "var(--danger, #f87171)",
      transform: "translateY(-1px)",
      boxShadow: "0 4px 12px -8px var(--shadowMedium)",
    },
    ":active": {
      transform: "translateY(0)",
    },
  },
  stopGenerationBtnIcon: {
    width: "10px",
    height: "10px",
    borderRadius: "var(--radius-xs)",
    backgroundColor: "currentColor",
  },
  stopGenerationBtnLabel: {
    lineHeight: 1,
  },

  /* ── VoiceInputButton ── */
  voiceBtn: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 0,
    borderStyle: "none",
    outline: "none",
    padding: 0,
    cursor: "pointer",
    transition: "all 0.25s cubic-bezier(0.25, 0.46, 0.45, 0.94)",
    flexShrink: 0,
    position: "relative",
    overflow: "hidden",
  },
  voiceBtnIdle: {
    backgroundColor: "var(--surfaceInset, var(--backgroundSecondary))",
    color: "var(--textMuted, var(--textSecondary))",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "var(--borderMuted, var(--borderLight))",
    boxShadow: "0 1px 2px var(--shadowLight)",
    ":hover": {
      backgroundColor: "var(--surfaceInteractiveHover, var(--backgroundTertiary))",
      color: "var(--primary)",
      borderColor: "var(--borderSubtle)",
      transform: "translateY(-1px)",
      boxShadow: "0 6px 14px -12px var(--shadowMedium)",
    },
  },
  voiceBtnRecording: {
    backgroundColor: "color-mix(in srgb, var(--error, #ef4444) 14%, var(--surfaceInset, var(--backgroundSecondary)))",
    color: "var(--error, #ef4444)",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "color-mix(in srgb, var(--error, #ef4444) 40%, var(--borderLight))",
    boxShadow:
      "0 0 0 3px color-mix(in srgb, var(--error, #ef4444) 18%, transparent), 0 8px 20px -12px var(--shadowMedium)",
    animationName: "voice-recording-pulse",
    animationDuration: "1.8s",
    animationTimingFunction: "ease-in-out",
    animationIterationCount: "infinite",
    ":hover": {
      backgroundColor: "color-mix(in srgb, var(--error, #ef4444) 22%, var(--surfaceInset, var(--backgroundSecondary)))",
    },
  },
  voiceBtnProcessing: {
    backgroundColor: "color-mix(in srgb, var(--primary, #3b82f6) 12%, var(--surfaceInset, var(--backgroundSecondary)))",
    color: "var(--primary, #3b82f6)",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "color-mix(in srgb, var(--primary, #3b82f6) 35%, var(--borderLight))",
    boxShadow:
      "0 0 0 3px color-mix(in srgb, var(--primary, #3b82f6) 15%, transparent)",
    cursor: "progress",
  },
  voiceBtnCompact: {
    width: "32px",
    height: "32px",
    borderRadius: "50%",
  },
  voiceBtnInSend: {
    width: "var(--button-size, 36px)",
    height: "var(--button-size, 36px)",
    borderRadius: "50%",
    "@media (max-width: 768px)": {
      width: "40px",
      height: "40px",
    },
  },
  voiceDots: {
    display: "flex",
    alignItems: "center",
    gap: "3px",
  },
  voiceDot: {
    width: "4px",
    height: "4px",
    borderRadius: "50%",
    backgroundColor: "currentColor",
    animationName: "voice-dots-pulse",
    animationDuration: "1.2s",
    animationTimingFunction: "ease-in-out",
    animationIterationCount: "infinite",
  },
  voiceBars: {
    display: "flex",
    alignItems: "center",
    gap: "2px",
    height: "16px",
  },
  voiceBar: {
    width: "3px",
    height: "100%",
    borderRadius: "2px",
    backgroundColor: "currentColor",
    transformOrigin: "center bottom",
  },

  /* ── ScrollToTopButton / ScrollToBottomButton ── */
  scrollButtons: {
    "--scroll-button-size": "36px",
    position: "sticky",
    bottom: "calc(var(--message-input-height, 80px) + 16px)",
    alignSelf: "flex-end",
    width: "max-content",
    marginRight: "16px",
    marginTop: "-100px",
    zIndex: 4,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "6px",
    "@media (max-width: 768px)": {
      "--scroll-button-size": "32px",
      marginRight: "10px",
      bottom: "calc(var(--message-input-height, 70px) + 12px)",
    },
  },
  scrollToBottomButton: {
    width: "var(--scroll-button-size)",
    height: "var(--scroll-button-size)",
    minWidth: "var(--scroll-button-size)",
    minHeight: "var(--scroll-button-size)",
    aspectRatio: 1,
    boxSizing: "border-box",
    flex: "0 0 var(--scroll-button-size)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "var(--backgroundSecondary)",
    color: "var(--textSecondary)",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "var(--border)",
    borderRadius: "50%",
    boxShadow: "0 2px 8px rgba(0,0,0,0.1)",
    cursor: "pointer",
    opacity: 0,
    transform: "translateY(4px)",
    animationName: "scroll-btn-appear",
    animationDuration: "0.2s",
    animationTimingFunction: "cubic-bezier(0.16, 1, 0.3, 1)",
    animationFillMode: "forwards",
    transition:
      "background-color 0.15s, border-color 0.15s, transform 0.15s",
    ":hover": {
      backgroundColor: "var(--background)",
      borderColor: "var(--primary)",
      color: "var(--primary)",
      transform: "translateY(-1px)",
    },
  },

  /* ── ComposerSuggestionMenu (unified @mention / slash surface) ──
     Styles live in ComposerSuggestionMenu.tsx (stylex) with literal class
     hooks + narrow-container rules in chatStylexEscapeHatch.css. */

  /* ── CreateTaskModal ── */
  ctm: {
    display: "flex",
    flexDirection: "column",
    gap: "20px",
    padding: "4px 0",
  },
  ctmField: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  ctmLabel: {
    fontSize: "var(--fontSize-base)",
    fontWeight: 600,
    color: "var(--textSecondary)",
  },
  ctmInput: {
    width: "100%",
    padding: "9px 12px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "var(--border)",
    borderRadius: "var(--radius-md)",
    fontSize: "var(--fontSize-base)",
    lineHeight: "var(--leading-normal)",
    color: "var(--text)",
    backgroundColor: "var(--background)",
    outline: "none",
    boxSizing: "border-box",
    transition: "border-color 0.15s",
    ":focus": {
      borderColor: "var(--primary)",
    },
  },
  ctmInputMono: {
    fontFamily: "var(--font-mono, monospace)",
    fontSize: "var(--fontSize-sm)",
    lineHeight: "var(--leading-normal)",
  },
  ctmTextarea: {
    width: "100%",
    padding: "9px 12px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "var(--border)",
    borderRadius: "var(--radius-md)",
    fontSize: "var(--fontSize-base)",
    color: "var(--text)",
    backgroundColor: "var(--background)",
    outline: "none",
    resize: "vertical",
    boxSizing: "border-box",
    lineHeight: "var(--leading-relaxed)",
    transition: "border-color 0.15s",
    ":focus": {
      borderColor: "var(--primary)",
    },
  },
  ctmFreqRow: {
    display: "flex",
    gap: "6px",
  },
  ctmFreqBtn: {
    flex: 1,
    padding: "8px 4px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "var(--border)",
    borderRadius: "var(--radius-md)",
    fontSize: "var(--fontSize-base)",
    fontWeight: 600,
    color: "var(--textSecondary)",
    backgroundColor: "var(--backgroundSecondary)",
    cursor: "pointer",
    transition: "all 0.15s",
    ":hover": {
      borderColor: "var(--primary)",
      color: "var(--primary)",
    },
  },
  ctmFreqBtnActive: {
    borderColor: "var(--primary)",
    backgroundColor: "var(--primaryGhost, rgba(99,102,241,0.08))",
    color: "var(--primary)",
  },
  ctmTimeRow: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    flexWrap: "wrap",
  },
  ctmTimeLabel: {
    fontSize: "var(--fontSize-base)",
    color: "var(--textSecondary)",
  },
  ctmSelectWrap: {
    position: "relative",
    display: "inline-flex",
    alignItems: "center",
  },
  ctmSelect: {
    appearance: "none",
    WebkitAppearance: "none",
    padding: "8px 30px 8px 12px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "var(--border)",
    borderRadius: "var(--radius-md)",
    fontSize: "var(--fontSize-base)",
    color: "var(--text)",
    backgroundColor: "var(--background)",
    cursor: "pointer",
    outline: "none",
    transition: "border-color 0.15s",
    ":focus": {
      borderColor: "var(--primary)",
    },
  },
  ctmSelectArrow: {
    position: "absolute",
    right: "9px",
    pointerEvents: "none",
    color: "var(--textTertiary)",
  },
  ctmCronPreview: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    flexWrap: "wrap",
    padding: "8px 12px",
    backgroundColor: "var(--backgroundSecondary)",
    borderRadius: "var(--radius-md)",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "var(--borderLight)",
  },
  ctmCronDesc: {
    fontSize: "var(--fontSize-sm)",
    color: "var(--textSecondary)",
    flex: 1,
    lineHeight: "var(--leading-normal)",
  },
  ctmCronCode: {
    fontFamily: "var(--font-mono, monospace)",
    fontSize: "var(--fontSize-sm)",
    color: "var(--primary)",
    backgroundColor: "var(--primaryGhost, rgba(99,102,241,0.08))",
    padding: "2px 8px",
    borderRadius: "var(--radius-sm)",
  },
  ctmAgentHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  ctmReload: {
    backgroundColor: "transparent",
    borderWidth: 0,
    borderStyle: "none",
    color: "var(--textTertiary)",
    cursor: "pointer",
    padding: "2px",
    display: "flex",
    alignItems: "center",
    ":hover": {
      color: "var(--primary)",
    },
  },
  ctmHint: {
    fontSize: "var(--fontSize-sm)",
    color: "var(--textSecondary)",
    margin: 0,
    lineHeight: "var(--leading-normal)",
  },
  ctmAgentList: {
    display: "flex",
    flexDirection: "column",
    gap: "3px",
    maxHeight: "160px",
    overflowY: "auto",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "var(--border)",
    borderRadius: "var(--radius-md)",
    padding: "4px",
  },
  ctmAgentBtn: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "8px 12px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "transparent",
    borderRadius: "var(--radius-sm)",
    fontSize: "var(--fontSize-base)",
    color: "var(--text)",
    backgroundColor: "transparent",
    cursor: "pointer",
    textAlign: "left",
    transition: "all 0.15s",
    ":hover": {
      backgroundColor: "var(--backgroundHover)",
    },
  },
  ctmAgentBtnActive: {
    borderColor: "var(--primary)",
    backgroundColor: "var(--primaryGhost, rgba(99,102,241,0.08))",
  },
  ctmAgentName: {
    flex: 1,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  ctmBadge: {
    fontSize: "var(--fontSize-xs)",
    fontWeight: 700,
    padding: "2px 6px",
    borderRadius: "var(--radius-sm)",
    marginLeft: "8px",
    flexShrink: 0,
  },
  ctmBadgeCli: {
    backgroundColor: "#e0f2fe",
    color: "#0369a1",
  },
  ctmBadgeLocal: {
    backgroundColor: "#dcfce7",
    color: "#166534",
  },
  ctmError: {
    fontSize: "var(--fontSize-sm)",
    color: "var(--error, #dc2626)",
    margin: 0,
    padding: "8px 12px",
    backgroundColor: "var(--errorGhost, rgba(220,38,38,0.06))",
    borderRadius: "var(--radius-md)",
  },
  ctmActions: {
    display: "flex",
    justifyContent: "flex-end",
    gap: "8px",
    paddingTop: "4px",
  },

  /* ── ImageConfigRow ── */
  imageConfigRow: {
    display: "flex",
    gap: "8px",
    alignItems: "center",
    marginBottom: "8px",
    fontSize: "var(--fontSize-sm)",
    color: "var(--textSecondary)",
    flexWrap: "wrap",
  },
  imageConfigRowSelect: {
    width: "auto",
    minWidth: 0,
    flex: "0 0 auto",
    color: "var(--text)",
    fontSize: "var(--fontSize-sm)",
  },

  /* ── MessageInputContainer & Core ── */
  container: {
    width: "100%",
    position: "relative",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    boxSizing: "border-box",
    padding: "0 var(--container-padding, 16px)",
    "@media (max-width: 768px)": {
      padding: "0 var(--container-padding, 8px)",
    },
  },
  wrapper: {
    width: "100%",
    maxWidth: "var(--chat-max-width, 840px)",
    position: "relative",
    display: "flex",
    flexDirection: "column",
  },
  controls: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
  },
  controlsLeft: {
    display: "flex",
    alignItems: "center",
    gap: "var(--space-3)",
  },
  controlsRight: {
    display: "flex",
    alignItems: "center",
    gap: "var(--space-3)",
  },
  canvasEditChip: {
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
    maxWidth: "100%",
    margin: "0 0 6px 0",
    padding: "4px 8px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "var(--borderMuted, var(--border))",
    borderRadius: "var(--radius-xs)",
    backgroundColor: "var(--surfaceRaised, var(--backgroundSecondary))",
    color: "var(--textSecondary)",
    fontSize: "var(--fontSize-sm)",
    boxShadow: "0 2px 6px -4px var(--shadowMedium)",
  },
  canvasEditChipActionable: {
    borderColor: "color-mix(in srgb, var(--primary) 28%, var(--border))",
  },
  canvasEditChipLabel: {
    flex: 1,
    minWidth: 0,
    margin: 0,
    padding: 0,
    borderWidth: 0,
    borderStyle: "none",
    backgroundColor: "transparent",
    color: "inherit",
    font: "inherit",
    textAlign: "left",
    cursor: "pointer",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    ":hover": {
      color: "var(--primary)",
    },
  },
  pasteChips: {
    display: "flex",
    flexWrap: "wrap",
    gap: "6px",
    margin: "0 0 4px",
  },
  confirmBar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "12px",
    maxWidth: "100%",
    margin: "0 0 10px 0",
    padding: "9px 10px 9px 12px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "color-mix(in srgb, var(--error) 32%, var(--border))",
    borderRadius: "var(--radius-sm)",
    backgroundColor: "color-mix(in srgb, var(--errorGhost, rgba(239, 68, 68, 0.08)) 72%, var(--surfaceRaised, var(--background)))",
    color: "var(--text)",
    boxShadow: "0 4px 12px -8px var(--shadowMedium)",
    "@media (max-width: 640px)": {
      marginLeft: 0,
    },
  },
  confirmText: {
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: "var(--fontSize-sm)",
    color: "var(--text)",
  },
  confirmActions: {
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
    flexShrink: 0,
  },
  confirmSecondary: {
    height: "30px",
    padding: "0 10px",
    borderRadius: "var(--radius-xs)",
    fontSize: "var(--fontSize-sm)",
    fontWeight: 600,
    cursor: "pointer",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "var(--borderMuted, var(--border))",
    whiteSpace: "nowrap",
    backgroundColor: "var(--surfaceRaised, var(--background))",
    color: "var(--textSecondary)",
    ":disabled": {
      cursor: "not-allowed",
      opacity: 0.65,
    },
  },
  confirmDanger: {
    height: "30px",
    padding: "0 10px",
    borderRadius: "var(--radius-xs)",
    fontSize: "var(--fontSize-sm)",
    fontWeight: 600,
    cursor: "pointer",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "var(--error)",
    whiteSpace: "nowrap",
    backgroundColor: "var(--error)",
    color: "#fff",
    ":disabled": {
      cursor: "not-allowed",
      opacity: 0.65,
    },
  },
  runningProcessesPanel: {
    margin: "0 0 10px 48px",
    padding: "8px 12px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "var(--borderMuted, var(--border))",
    borderRadius: "var(--radius-sm)",
    backgroundColor: "var(--surfaceOverlay, var(--surfaceRaised, var(--backgroundSecondary)))",
    color: "var(--textSecondary)",
    boxShadow: "0 10px 24px -22px var(--shadowMedium)",
    boxSizing: "border-box",
    maxWidth: "calc(100% - 48px)",
    display: "flex",
    flexDirection: "column",
    gap: "4px",
    "@media (max-width: 768px)": {
      marginLeft: 0,
      maxWidth: "100%",
    },
  },
  runningProcessesTitle: {
    color: "var(--text)",
    fontSize: "var(--fontSize-sm)",
    fontWeight: 700,
    lineHeight: "var(--leading-normal)",
  },
  runningProcessesRow: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    minWidth: 0,
  },
  runningProcessesLabel: {
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: "var(--fontSize-sm)",
    color: "var(--textSecondary)",
  },
  runningProcessesPid: {
    flexShrink: 0,
    color: "var(--textTertiary)",
    fontSize: "var(--fontSize-xs)",
    fontVariantNumeric: "tabular-nums",
  },
  runningProcessesStopBtn: {
    flexShrink: 0,
    display: "inline-flex",
    alignItems: "center",
    gap: "4px",
    padding: "2px 8px",
    borderRadius: "var(--radius-sm)",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "var(--danger, #f87171)",
    backgroundColor: "color-mix(in srgb, var(--danger, #f87171) 14%, transparent)",
    color: "var(--danger, #f87171)",
    fontSize: "var(--fontSize-xs)",
    fontWeight: 500,
    cursor: "pointer",
    transition: "background 0.15s ease",
    ":hover": {
      backgroundColor: "color-mix(in srgb, var(--danger, #f87171) 22%, transparent)",
    },
    ":disabled": {
      opacity: 0.5,
      cursor: "not-allowed",
    },
  },
  textareaWrap: {
    position: "relative",
    flex: 1,
    display: "flex",
  },
  textarea: {
    flex: 1,
    minHeight: "24px",
    maxHeight: "360px",
    padding: "4px 0",
    boxSizing: "border-box",
    fontSize: "var(--fontSize-base)",
    lineHeight: "var(--leading-relaxed)",
    borderRadius: 0,
    borderWidth: 0,
    borderStyle: "none",
    borderColor: "transparent",
    backgroundColor: "transparent",
    color: "var(--text)",
    resize: "none",
    outline: "none",
    boxShadow: "none",
    transition:
      "height 0.15s ease-out, max-height 0.15s ease-out",
    "::placeholder": {
      color: "var(--textTertiary)",
      opacity: 0.8,
    },
    ":focus": {
      backgroundColor: "transparent",
      borderColor: "transparent",
      boxShadow: "none",
      outline: "none",
    },
    ":disabled": {
      opacity: 0.6,
      backgroundColor: "transparent",
      cursor: "not-allowed",
      borderColor: "transparent",
      boxShadow: "none",
    },
  },
  indicator: {
    position: "absolute",
    top: "-40px",
    right: "var(--container-padding)",
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
    padding: "6px 12px",
    borderRadius: "var(--radius-xs)",
    backgroundColor: "var(--surfaceInset, var(--backgroundSecondary))",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "var(--borderMuted, var(--border))",
    fontSize: "var(--fontSize-sm)",
    color: "var(--textSecondary)",
    boxShadow: "0 8px 20px -18px var(--shadowMedium)",
    animationName: "indicator-fade-in",
    animationDuration: "0.2s",
    animationTimingFunction: "ease",
  },
  indicatorStatus: {
    width: "8px",
    height: "8px",
    borderRadius: "50%",
    backgroundColor: "var(--primary)",
    animationName: "indicator-pulse",
    animationDuration: "1.5s",
    animationTimingFunction: "ease-in-out",
    animationIterationCount: "infinite",
  },
  indicatorText: {
    fontWeight: 500,
  },
  counter: {
    position: "absolute",
    bottom: "12px",
    right: "16px",
    fontSize: "var(--fontSize-xs)",
    color: "var(--textTertiary)",
    pointerEvents: "none",
    userSelect: "none",
    opacity: 0,
    transition: "opacity 0.2s ease",
  },
  counterVisible: {
    opacity: 1,
  },
  bottomRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "var(--space-2)",
    width: "100%",
    marginTop: "var(--space-2)",
    flexWrap: "nowrap",
  },
  tools: {
    display: "flex",
    alignItems: "center",
    gap: "var(--space-2)",
    flex: 1,
    minWidth: 0,
    overflow: "visible",
  },
  sendArea: {
    display: "flex",
    alignItems: "center",
    gap: "var(--space-2)",
    flexShrink: 0,
    marginLeft: "auto",
  },
  browseContextIndicator: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    maxWidth: "100%",
    padding: "4px 10px",
    marginBottom: "var(--space-2, 8px)",
    borderRadius: "999px",
    backgroundColor: "rgba(37, 99, 235, 0.08)",
    color: "#2563eb",
    fontSize: "var(--fontSize-xs, 12px)",
    lineHeight: 1.4,
    cursor: "default",
    userSelect: "none",
  },
  browseContextIcon: {
    flexShrink: 0,
  },
  browseContextHost: {
    flexShrink: 0,
    fontWeight: 600,
  },
  browseContextTitle: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    color: "var(--textSecondary, #64748b)",
    maxWidth: "220px",
  },
  dialogUsagePopover: {
    width: "min(260px, calc(100vw - 24px))",
    padding: "12px 14px",
  },
  dialogUsagePanel: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    minWidth: 0,
  },
  dialogUsageRow: {
    display: "flex",
    alignItems: "baseline",
    justifyContent: "space-between",
    gap: "12px",
    minWidth: 0,
  },
  dialogUsageRowMain: {
    gap: "16px",
  },
  dialogUsageHeadline: {
    margin: 0,
    minWidth: 0,
    fontSize: "var(--fontSize-sm)",
    fontWeight: 600,
    color: "var(--text)",
    fontVariantNumeric: "tabular-nums",
    lineHeight: 1.35,
  },
  dialogUsageHeadlineMuted: {
    fontWeight: 500,
    color: "var(--textTertiary)",
  },
  dialogUsageIo: {
    margin: 0,
    fontSize: "var(--fontSize-xs)",
    lineHeight: 1.35,
    color: "var(--textTertiary)",
    fontVariantNumeric: "tabular-nums",
  },
  dialogUsageIoSep: {
    margin: "0 0.35em",
    opacity: 0.7,
  },
  dialogUsageBillingValue: {
    fontSize: "var(--fontSize-xs)",
    fontWeight: 600,
    color: "var(--textSecondary)",
    fontVariantNumeric: "tabular-nums",
    whiteSpace: "nowrap",
    flexShrink: 0,
  },
  dialogUsageMeter: {
    width: "100%",
    margin: 0,
  },
  dialogUsageCompression: {
    margin: 0,
    fontSize: "var(--fontSize-xs)",
    color: "var(--textTertiary)",
  },
});
