import * as stylex from "@stylexjs/stylex";

/**
 * 侧边栏样式体系（sidebar.css → StyleX 1:1 迁出，2026-08-30）。
 * ChatSidebar, AllViewSidebar, CategorySection, SidebarUserSection, etc.
 *
 * 与原 CSS 保持 1:1：同一元素、同一声明、同值。
 * 运行时 :root 变量由 GlobalThemeController 注入，var(--global-*) 原样保留。
 */
export const sidebarStyles = stylex.create({
  /* ── ChatSidebar Alignment System ── */
  chatSidebar: {
    "--sidebar-gutter": "8px",
    "--sidebar-row-pad": "8px",
    "--sidebar-icon-size": "20px",
    "--sidebar-gap-x": "8px",
    "--sidebar-row-height": "32px",
    display: "flex",
    flexDirection: "column",
    height: "100%",
    backgroundColor: "transparent",
    borderRightWidth: "1px",
    borderRightStyle: "solid",
    borderRightColor: "var(--borderSubtle)",
    fontSize: "var(--fontSize-base)",
    userSelect: "none",
    WebkitTapHighlightColor: "transparent",
  },

  /* 1. 顶栏 Block (探索 + 搜索) */
  topBar: {
    padding: "8px var(--sidebar-gutter) 4px",
    display: "flex",
    alignItems: "center",
    gap: "var(--sidebar-gap-x)",
    minWidth: 0,
    height: "40px",
    boxSizing: "border-box",
  },
  topExplore: {
    flex: 1,
    margin: 0,
    width: "auto",
    minHeight: "var(--sidebar-row-height)",
    padding: "0 var(--sidebar-row-pad)",
  },
  topExploreMenuIcon: {
    backgroundImage: "linear-gradient(135deg, hsl(262 60% 55%), hsl(210 70% 52%))",
    color: "#fff",
    width: "var(--sidebar-icon-size)",
    height: "var(--sidebar-icon-size)",
    borderRadius: "var(--radius-sm)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  searchBtn: {
    boxSizing: "border-box",
    width: "var(--sidebar-header-control-size, 28px)",
    height: "var(--sidebar-header-control-size, 28px)",
    minHeight: "var(--sidebar-header-control-size, 28px)",
    flexShrink: 0,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 0,
    borderWidth: 0,
    borderStyle: "none",
    borderRadius: "var(--sidebar-header-control-radius, var(--radius-md, 6px))",
    backgroundColor: "transparent",
    color: "var(--textSecondary, var(--textMuted))",
    cursor: "pointer",
    transition: "color 0.15s ease, background-color 0.15s ease",
    ":hover": {
      color: "var(--primary)",
      backgroundColor: "var(--hoverBg)",
    },
    ":focus-visible": {
      color: "var(--primary)",
      backgroundColor: "var(--hoverBg)",
      outline: "none",
    },
  },
  /* 自逃生舱 .ChatSidebar__header-wrapper--space 迁入（2026-08-31） */
  headerWrapperSpace: {
    marginTop: "4px",
    paddingTop: "6px",
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: "color-mix(in srgb, var(--border) 45%, transparent)",
  },
  createRow: {
    padding: "2px 8px 4px",
    display: "flex",
    alignItems: "center",
    gap: "var(--space-2)",
    minWidth: 0,
    whiteSpace: "nowrap",
  },
  scopeWrapper: {
    minWidth: 0,
    overflow: "hidden",
  },
  searchWrapper: {
    boxSizing: "border-box",
    padding: "var(--space-3) var(--space-3) var(--space-2)",
    minWidth: 0,
  },
  searchTooltip: {
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
  },
  pinnedBlock: {
    padding: "4px var(--sidebar-gutter)",
    marginBottom: "var(--space-1)",
    borderBottomWidth: 0,
    borderBottomStyle: "none",
    flexShrink: 0,
  },
  pinnedBlockWrapper: {
    display: "flex",
    flexDirection: "column",
    gap: "4px",
  },
  scrollArea: {
    flex: 1,
    minHeight: 0,
    overflowY: "auto",
    overflowX: "hidden",
    display: "flex",
    flexDirection: "column",
    padding: "4px var(--sidebar-gutter) 0",
    scrollbarWidth: "thin",
    overscrollBehavior: "contain",
  },
  content: {
    flex: "0 1 auto",
    display: "flex",
    flexDirection: "column",
    gap: "var(--space-2)",
    paddingBottom: "var(--space-3)",
  },
  contentSingleSection: {
    flex: 1,
    minHeight: 0,
  },
  section: {
    display: "flex",
    flexDirection: "column",
    minHeight: 0,
  },
  sectionEmpty: {
    opacity: 0.6,
  },
  draggableContainer: {
    borderRadius: "var(--radius-sm)",
    transition: "background-color 0.15s, box-shadow 0.15s",
    display: "flex",
    flexDirection: "column",
    minHeight: 0,
  },
  draggableContainerDragOverCategory: {
    backgroundColor: "var(--primaryGhost)",
    outline: "2px dashed var(--primary)",
  },
  draggableContainerDragOverItem: {
    backgroundColor: "var(--successGhost)",
    outline: "2px dashed var(--success)",
  },

  /* ── CategorySection ── */
  categorySection: {
    position: "relative",
    display: "flex",
    flexDirection: "column",
    minHeight: 0,
  },
  categoryContentWrapper: {
    display: "grid",
    gridTemplateRows: "1fr",
    transition: "grid-template-rows 0.25s cubic-bezier(0.4, 0, 0.2, 1)",
    overflow: "clip",
    minHeight: 0,
  },
  categoryContentWrapperCollapsed: {
    gridTemplateRows: "0fr",
    flex: "0 0 0px",
  },
  categoryContentInner: {
    minHeight: 0,
    overflow: "hidden",
    maxHeight: "min(420px, 55vh)",
    display: "flex",
    flexDirection: "column",
  },
  scroller: {
    display: "block",
    padding: 0,
    margin: 0,
    overflow: "auto",
    contain: "style",
    scrollbarWidth: "none",
    flex: "1 1 auto",
    minHeight: 0,
    width: "100%",
    overscrollBehavior: "contain",
  },
  overflowHint: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "4px",
    padding: "5px 8px 7px",
    fontSize: "var(--fontSize-xs)",
    color: "var(--textTertiary)",
    backgroundColor: "var(--surfaceSidebar, var(--background))",
    borderTopWidth: "1px",
    borderTopStyle: "dashed",
    borderTopColor: "var(--borderLight)",
    cursor: "default",
    userSelect: "none",
    flexShrink: 0,
    transition: "color 0.15s, background 0.15s",
    ":hover": {
      color: "var(--textSecondary)",
      backgroundColor: "var(--backgroundHover)",
    },
  },

  /* ── ChatSidebarEmptySearch ── */
  emptySearch: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    padding: "80px 24px",
    textAlign: "center",
    animationName: "chatSidebarEmptyFadeIn",
    animationDuration: "0.25s",
    animationTimingFunction: "ease",
  },
  emptySearchIllustration: {
    width: "64px",
    height: "64px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "var(--backgroundSecondary)",
    borderRadius: "var(--radius-md)",
    color: "var(--textTertiary)",
    marginBottom: "16px",
    boxShadow: "inset 0 1px 2px rgba(0, 0, 0, 0.02)",
  },
  emptySearchText: {
    fontSize: "var(--fontSize-base)",
    fontWeight: 600,
    color: "var(--textSecondary)",
    margin: "0 0 4px",
  },
  emptySearchSubtext: {
    fontSize: "var(--fontSize-sm)",
    color: "var(--textSecondary)",
    margin: "0 0 24px",
  },
  emptySearchClearBtn: {
    padding: "8px 20px",
    backgroundColor: "var(--primary)",
    color: "white",
    borderWidth: 0,
    borderStyle: "none",
    borderRadius: "var(--radius-xs)",
    fontSize: "var(--fontSize-sm)",
    fontWeight: 600,
    cursor: "pointer",
    transition: "all 0.15s",
    ":hover": {
      transform: "translateY(-1px)",
      filter: "brightness(1.05)",
      boxShadow: "var(--shadow3)",
    },
    ":active": {
      transform: "translateY(0)",
    },
  },

  /* ── AllViewSidebar ── */
  allViewSidebar: {
    display: "flex",
    flexDirection: "column",
    flex: 1,
    minHeight: 0,
    overflow: "hidden",
    backgroundColor: "transparent",
    color: "var(--text)",
  },
  allViewRecentBar: {
    display: "flex",
    alignItems: "center",
    gap: "var(--space-2)",
    minHeight: "var(--sidebarItemHeight, var(--control-md))",
    padding: "var(--space-1) var(--space-2)",
    margin: "var(--space-2) var(--space-2) var(--space-2)",
    borderRadius: "var(--radius-md)",
    backgroundColor: "var(--surfaceSidebar, var(--background))",
    flexShrink: 0,
  },
  allViewBatchToggle: {
    marginLeft: "auto",
  },
  allViewRecentContent: {
    display: "flex",
    flexDirection: "column",
    gap: "var(--space-1)",
    padding: "4px var(--sidebar-gutter)",
    flex: 1,
    minHeight: 0,
    overflow: "hidden",
  },
  navGroupFavorites: {
    display: "flex",
    flexDirection: "column",
    flexShrink: 0,
    margin: "4px 0 6px",
    padding: 0,
  },
  navRowFavoritesHeader: {
    minHeight: "26px",
    height: "26px",
    margin: "0 var(--sidebar-gutter) 2px",
    padding: "0 4px",
    color: "var(--textTertiary)",
    fontSize: "var(--fontSize-xs)",
    fontWeight: 600,
    letterSpacing: "0.02em",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    borderRadius: "var(--radius-sm)",
    userSelect: "none",
    transition: "background-color 0.15s ease, color 0.15s ease",
    ":hover": {
      backgroundColor: "var(--hoverBg)",
      color: "var(--textSecondary)",
    },
  },
  favoritesToggle: {
    display: "inline-flex",
    alignItems: "center",
    gap: "var(--sidebar-gap-x)",
    flex: 1,
    minWidth: 0,
    height: "100%",
    padding: "0 2px",
    margin: 0,
    borderWidth: 0,
    borderStyle: "none",
    backgroundColor: "transparent",
    color: "inherit",
    font: "inherit",
    textAlign: "left",
    cursor: "pointer",
    borderRadius: "var(--radius-xs)",
    ":focus-visible": {
      outline: "none",
      boxShadow: "0 0 0 2px var(--focusRing, var(--primary))",
    },
    ":disabled": {
      cursor: "default",
      opacity: 0.6,
    },
  },
  favoritesToggleStar: {
    flexShrink: 0,
    color: "var(--amber500, #f59e0b)",
  },
  favoritesToggleLabel: {
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontWeight: 600,
  },
  favoritesToggleChevron: {
    flexShrink: 0,
    color: "var(--textTertiary)",
    transition: "transform 0.18s cubic-bezier(0.4, 0, 0.2, 1)",
    transform: "rotate(0deg)",
  },
  favoritesToggleChevronCollapsed: {
    transform: "rotate(-90deg)",
  },
  favoritesLink: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "2px 6px",
    borderRadius: "var(--radius-xs)",
    color: "inherit",
    textDecoration: "none",
    fontSize: "var(--fontSize-xs)",
    fontWeight: 500,
    lineHeight: 1,
    flexShrink: 0,
    transition: "color 0.15s ease, background-color 0.15s ease",
    ":hover": {
      color: "var(--primary)",
      backgroundColor: "var(--hoverBg)",
    },
    ":focus-visible": {
      outline: "none",
      boxShadow: "0 0 0 2px var(--focusRing, var(--primary))",
    },
  },
  favoritesCount: {
    fontVariantNumeric: "tabular-nums",
    opacity: 0.85,
  },
  navRow: {
    display: "flex",
    alignItems: "center",
    gap: "var(--sidebar-gap-x)",
    minHeight: "var(--sidebar-row-height)",
    padding: "0 var(--sidebar-row-pad)",
    margin: "2px var(--sidebar-gutter)",
    borderRadius: "var(--radius-md)",
    backgroundColor: "transparent",
    color: "var(--textSecondary)",
    borderWidth: 0,
    borderStyle: "none",
    cursor: "pointer",
    transition: "background 0.15s ease, color 0.15s ease",
    textAlign: "left",
    width: "calc(100% - var(--sidebar-gutter) * 2)",
    boxSizing: "border-box",
    fontSize: "var(--fontSize-sm)",
    fontWeight: 500,
    textDecoration: "none",
    ":hover": {
      backgroundColor: "color-mix(in srgb, var(--text) 6%, transparent)",
      color: "var(--text)",
    },
    ":focus-visible": {
      backgroundColor: "color-mix(in srgb, var(--text) 6%, transparent)",
      color: "var(--text)",
      outline: "none",
    },
  },
  navRowActive: {
    backgroundColor: "color-mix(in srgb, var(--primary) 12%, transparent)",
    color: "var(--text)",
    fontWeight: 600,
    boxShadow: "inset 0 0 0 1px color-mix(in srgb, var(--primary) 20%, transparent)",
  },
  favoritesBlock: {
    margin: "2px var(--sidebar-gutter) 0",
    padding: 0,
  },
  chatSidebarNavRowDivider: {
    marginTop: "var(--space-1)",
    marginBottom: "var(--space-1)",
    paddingBottom: "var(--space-2)",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: "color-mix(in srgb, var(--border) 55%, transparent)",
  },
  addCategoryRow: {
    display: "flex",
    alignItems: "center",
    gap: "var(--sidebar-gap-x)",
    minHeight: "var(--sidebar-row-height)",
    padding: "0 var(--sidebar-row-pad)",
    margin: "6px var(--sidebar-gutter) 4px",
    width: "calc(100% - var(--sidebar-gutter) * 2)",
    boxSizing: "border-box",
    borderWidth: "1px",
    borderStyle: "dashed",
    borderColor: "color-mix(in srgb, var(--primary) 35%, var(--border, #e4e4e7))",
    borderRadius: "var(--radius-md)",
    backgroundColor: "color-mix(in srgb, var(--primary) 4%, transparent)",
    color: "var(--primary)",
    fontSize: "var(--fontSize-sm)",
    fontWeight: 600,
    letterSpacing: "0.01em",
    cursor: "pointer",
    transition: "color 0.15s ease, background-color 0.15s ease, border-color 0.15s ease, box-shadow 0.15s ease",
    ":hover": {
      backgroundColor: "color-mix(in srgb, var(--primary) 12%, transparent)",
      borderColor: "color-mix(in srgb, var(--primary) 70%, var(--border, #e4e4e7))",
      color: "var(--primary)",
      boxShadow: "0 0 0 1px color-mix(in srgb, var(--primary) 18%, transparent)",
    },
    ":active": {
      backgroundColor: "color-mix(in srgb, var(--primary) 16%, transparent)",
    },
    ":focus-visible": {
      outline: "2px solid color-mix(in srgb, var(--primary) 55%, transparent)",
      outlineOffset: "2px",
    },
  },

  /* 自逃生舱 .ChatSidebar__add-category-row svg 迁入（2026-08-31） */
  addCategoryRowIcon: {
    flexShrink: 0,
    color: "inherit",
    paddingTop: "3px",
    paddingRight: "3px",
    paddingBottom: "3px",
    paddingLeft: "3px",
    borderRadius: "var(--radius-xs, 4px)",
    backgroundColor: "color-mix(in srgb, var(--primary) 14%, transparent)",
    boxSizing: "content-box",
  },

  /* ── SidebarTypeFilter ── */
  sidebarTypeFilterShell: {
    display: "flex",
    alignItems: "center",
    minHeight: "32px",
    margin: "2px var(--sidebar-gutter) 4px",
    padding: "0 2px",
    borderRadius: "var(--radius-md)",
    transition: "background 0.15s ease",
    ":hover": {
      backgroundColor: "var(--hoverBg)",
    },
  },
  sidebarTypeFilter: {
    display: "flex",
    alignItems: "center",
    gap: "2px",
    flex: 1,
    minWidth: 0,
  },
  sidebarTypeFilterDisabled: {
    opacity: 0.5,
    pointerEvents: "none",
  },
  sidebarTypeFilterButton: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: "24px",
    height: "24px",
    minWidth: "24px",
    padding: 0,
    borderWidth: 0,
    borderStyle: "none",
    borderRadius: "var(--radius-sm)",
    backgroundColor: "transparent",
    color: "var(--textTertiary)",
    cursor: "pointer",
    transition: "background 0.15s ease, color 0.15s ease",
    ":hover": {
      backgroundColor: "var(--backgroundHover)",
      color: "var(--text)",
    },
  },
  sidebarTypeFilterButtonActive: {
    backgroundColor: "var(--primaryGhost)",
    color: "var(--primary)",
    boxShadow: "inset 0 0 0 1px color-mix(in srgb, var(--primary) 20%, transparent)",
  },

  /* ── AllView item & list elements ── */
  allViewBadge: {
    flexShrink: 0,
    minWidth: "18px",
    height: "18px",
    padding: "0 5px",
    borderRadius: "var(--radius-xs)",
    fontSize: "11px",
    fontWeight: 600,
    lineHeight: "18px",
    textAlign: "center",
    backgroundColor: "var(--backgroundSecondary)",
    color: "var(--textSecondary)",
    transition: "opacity 0.15s ease",
  },
  allViewMoreIcon: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "22px",
    height: "22px",
    flexShrink: 0,
    marginLeft: "auto",
    borderWidth: 0,
    borderStyle: "none",
    backgroundColor: "transparent",
    color: "var(--textTertiary)",
    borderRadius: "var(--radius-sm)",
    cursor: "pointer",
    transition: "color 0.15s ease, background 0.15s ease",
    ":hover": {
      color: "var(--primary)",
      backgroundColor: "var(--backgroundHover)",
    },
  },
  allViewMenuLabel: {
    flex: 1,
    minWidth: 0,
    fontWeight: 600,
  },
  allViewSection: {
    display: "flex",
    alignItems: "center",
    minHeight: "44px",
    padding: "0 4px",
  },
  allViewSectionFill: {
    flex: 1,
    minHeight: 0,
    display: "flex",
    flexDirection: "column",
    alignItems: "stretch",
  },
  allViewSectionHeader: {
    display: "flex",
    alignItems: "center",
    gap: "var(--space-3)",
    minWidth: 0,
    flex: 1,
    padding: "var(--space-2) 10px",
    backgroundColor: "transparent",
    borderWidth: 0,
    borderStyle: "none",
    borderRadius: "var(--radius-md)",
    color: "var(--text)",
    cursor: "default",
    textAlign: "left",
  },
  allViewSectionState: {
    fontSize: "var(--fontSize-xs)",
    color: "var(--textTertiary)",
  },
  allViewSectionPreview: {
    display: "flex",
    flexDirection: "column",
    gap: "2px",
    padding: "0 4px 0 16px",
    minHeight: 0,
  },
  allViewListItem: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "var(--space-2)",
    width: "100%",
    minHeight: "34px",
    padding: "7px 10px",
    backgroundColor: "transparent",
    borderWidth: 0,
    borderStyle: "none",
    borderRadius: "var(--radius-md)",
    color: "var(--text)",
    cursor: "pointer",
    transition: "background 0.12s ease",
    textAlign: "left",
    fontSize: "var(--fontSize-sm)",
    ":hover": {
      backgroundColor: "var(--backgroundHover)",
    },
  },
  allViewItemTitle: {
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  allViewItemMeta: {
    fontSize: "var(--fontSize-xs)",
    color: "var(--textTertiary)",
    flexShrink: 0,
    maxWidth: "110px",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  allViewPreviewEmpty: {
    padding: "8px 10px",
    color: "var(--textTertiary)",
    fontSize: "var(--fontSize-sm)",
  },
  allViewEmptyState: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    padding: "48px 16px",
    color: "var(--textTertiary, #a1a1aa)",
    textAlign: "center",
  },
  allViewEmptyIcon: {
    marginBottom: "12px",
    opacity: 0.5,
  },
  allViewEmptyText: {
    fontSize: "13px",
  },
  allViewSearchGroup: {
    display: "flex",
    flexDirection: "column",
    gap: "2px",
    minHeight: 0,
  },
  allViewSearchGroupTitle: {
    padding: "8px 10px 4px",
    fontSize: "var(--fontSize-xs)",
    color: "var(--textTertiary)",
    fontWeight: 600,
    letterSpacing: "0.02em",
    textTransform: "uppercase",
  },
  allViewRecentList: {
    display: "flex",
    flexDirection: "column",
    flex: 1,
    minHeight: 0,
    overflow: "hidden",
  },

  /* ── SidebarSkeleton ── */
  sidebarSkeleton: {
    display: "flex",
    flexDirection: "column",
    gap: "var(--space-2)",
    padding: "var(--space-2) var(--sidebar-gutter)",
  },
  sidebarSkeletonItem: {
    display: "flex",
    alignItems: "center",
    gap: "var(--sidebar-gap-x)",
    height: "var(--sidebar-row-height)",
    padding: "0 var(--sidebar-row-pad)",
    borderRadius: "var(--radius-md)",
  },
  sidebarSkeletonIcon: {
    width: "var(--sidebar-icon-size)",
    height: "var(--sidebar-icon-size)",
    borderRadius: "var(--radius-sm)",
    backgroundColor: "var(--surfaceOverlay, var(--backgroundSecondary))",
    flexShrink: 0,
    animationName: "sidebarSkeletonPulse",
    animationDuration: "1.5s",
    animationIterationCount: "infinite",
    animationTimingFunction: "ease-in-out",
  },
  sidebarSkeletonText: {
    height: "12px",
    borderRadius: "var(--radius-xs)",
    backgroundColor: "var(--surfaceOverlay, var(--backgroundSecondary))",
    animationName: "sidebarSkeletonPulse",
    animationDuration: "1.5s",
    animationIterationCount: "infinite",
    animationTimingFunction: "ease-in-out",
    flex: 1,
  },

  /* ── SidebarUserSection ── */
  sidebarUserSection: {
    marginTop: "auto",
    padding: "6px var(--sidebar-gutter) 8px",
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: "var(--borderSubtle)",
    flexShrink: 0,
    position: "relative",
    backgroundColor: "transparent",
  },
  sidebarUserSectionRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "4px",
    minWidth: 0,
  },
  sidebarUserSectionCardWrap: {
    display: "flex",
    alignItems: "center",
    gap: "2px",
    minWidth: 0,
  },
  sidebarUserSectionProfile: {
    flex: 1,
    minWidth: 0,
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "4px 6px",
    marginLeft: "-6px",
    borderRadius: "var(--radius-md, 8px)",
    borderWidth: 0,
    borderStyle: "none",
    backgroundColor: "transparent",
    color: "var(--text)",
    cursor: "pointer",
    transition: "background 0.15s ease",
    textAlign: "left",
    font: "inherit",
    ":hover": {
      backgroundColor: "var(--backgroundHover)",
    },
  },
  sidebarUserSectionUsername: {
    fontSize: "var(--fontSize-sm)",
    fontWeight: 500,
    color: "var(--text)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    minWidth: 0,
  },
  sidebarUserSectionActions: {
    display: "flex",
    alignItems: "center",
    gap: "2px",
    flexShrink: 0,
  },
  sidebarUserSectionToolWrap: {
    position: "relative",
  },
  sidebarUserSectionToolBtn: {
    width: "28px",
    height: "28px",
    padding: 0,
    borderRadius: "var(--radius-md, 8px)",
    borderWidth: 0,
    borderStyle: "none",
    backgroundColor: "transparent",
    color: "var(--textSecondary, var(--textMuted))",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    transition: "color 0.15s ease, background 0.15s ease",
    position: "relative",
    ":hover": {
      backgroundColor: "var(--backgroundHover)",
      color: "var(--text)",
    },
  },
  sidebarUserSectionToolBtnActive: {
    backgroundColor: "var(--primaryGhost)",
    color: "var(--primary)",
  },
  sidebarUserSectionMenuToggle: {
    flexShrink: 0,
    width: "24px",
    height: "24px",
    borderWidth: 0,
    borderStyle: "none",
    borderRadius: "var(--radius-md, 8px)",
    backgroundColor: "transparent",
    color: "var(--textTertiary, var(--textMuted))",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    transition: "color 0.15s ease, background 0.15s ease",
    ":hover": {
      color: "var(--text)",
      backgroundColor: "var(--backgroundHover)",
    },
  },
  /* 自逃生舱 .SidebarUserSection__menu-toggle.is-open 迁入（2026-08-31） */
  sidebarUserSectionMenuToggleOpen: {
    backgroundColor: "var(--surfaceInteractiveHover, var(--backgroundHover))",
    color: "var(--text)",
  },
  /* 自逃生舱 .SidebarUserSection__menu-toggle-icon 迁入（2026-08-31） */
  sidebarUserSectionMenuToggleIcon: {
    transitionProperty: "transform",
    transitionDuration: "0.15s",
    transitionTimingFunction: "ease",
  },
  /* 自逃生舱 .SidebarUserSection__menu-toggle.is-open .SidebarUserSection__menu-toggle-icon 迁入 */
  sidebarUserSectionMenuToggleIconOpen: {
    transform: "rotate(180deg)",
  },
  sidebarCoachmarkClose: {
    flexShrink: 0,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: "22px",
    height: "22px",
    margin: "-2px -4px 0 0",
    padding: 0,
    borderWidth: 0,
    borderStyle: "none",
    borderRadius: "var(--radius-sm, 4px)",
    backgroundColor: "transparent",
    color: "var(--textTertiary, var(--textMuted))",
    cursor: "pointer",
    ":hover": {
      color: "var(--text)",
      backgroundColor: "color-mix(in srgb, var(--text) 8%, transparent)",
      outline: "none",
    },
    ":focus-visible": {
      color: "var(--text)",
      backgroundColor: "color-mix(in srgb, var(--text) 8%, transparent)",
      outline: "none",
    },
  },
  sidebarUserSectionBadge: {
    position: "absolute",
    top: "-4px",
    right: "-6px",
    backgroundColor: "var(--red500, #ef4444)",
    color: "#fff",
    fontSize: "10px",
    fontWeight: "bold",
    minWidth: "16px",
    height: "16px",
    borderRadius: "var(--radius-xs)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "0 4px",
    boxShadow: "0 0 0 2px var(--surfaceSidebar, var(--background))",
  },
  sidebarUserSectionDropdown: {
    position: "absolute",
    bottom: "calc(100% + 8px)",
    left: "8px",
    right: "8px",
    minWidth: "unset",
    padding: "var(--popover-pad)",
    borderRadius: "var(--popover-radius)",
    backgroundColor: "var(--popover-bg)",
    backdropFilter: "blur(var(--popover-blur)) saturate(1.8)",
    WebkitBackdropFilter: "blur(var(--popover-blur)) saturate(1.8)",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "var(--popover-border)",
    boxShadow: "var(--popover-shadow)",
    opacity: 0,
    visibility: "hidden",
    transform: "translateY(var(--popover-travel)) scale(0.97)",
    transition:
      "opacity var(--popover-duration) var(--popover-ease), transform var(--popover-duration) var(--popover-ease), visibility var(--popover-duration)",
    zIndex: 1000,
    pointerEvents: "none",
    "@media (max-width: 768px)": {
      maxHeight: "72vh",
      overflowY: "auto",
      overscrollBehavior: "contain",
      WebkitOverflowScrolling: "touch",
    },
  },
  sidebarUserSectionDropdownOpen: {
    opacity: 1,
    visibility: "visible",
    transform: "translateY(0) scale(1)",
    pointerEvents: "auto",
  },
  sidebarUserSectionDropdownMenu: {
    minWidth: "250px",
  },
});
