// packages/cli/client/firstModelGeneratedPtcE2E.subprocessProbe.ts
//
// FIRST MODEL-GENERATED PTC E2E
//
// Proves: a program GENERATED BY A MODEL (captured as a real model completion,
// not hand-written by a human test author) can travel the EXISTING PTC path:
//
//   real runLocalAgentTurn
//     → real model response        (the MODEL_RESPONSE program below)
//     → parsePtcProgramOutput      (extract the program from model output)
//     → validatePtcProgramCode     (regex safety contract)
//     → existing QuickJS execution (executePtcQuickJsPrototype, QuickJS-WASM sandbox)
//     → CapabilitySdk from the CURRENT live turn
//     → real execShell  (runs a real `git status --short` in the turn workspace)
//     → real agents.run (routes through adapter.executeTool → real host seam)
//
// No new runtime / sandbox / tool-executor / authority abstraction. Reuses the
// existing wired PTC vertical slice (runLocalAgentTurn.__testPtcProgram).
//
// The FULL gate is exercised: the code that gets executed (`program.code`) is
// exactly what parsePtcProgramOutput extracted from the model output AND what
// validatePtcProgramCode accepted — never a pre-validated literal.
import {
  runLocalAgentTurn,
  parsePtcProgramOutput,
  validatePtcProgramCode,
  type AgentRuntimeHostAdapter,
  type AgentRuntimeToolCallInput,
} from "agent-runtime";

function assert(condition: unknown, message: string): asserts condition {
  if (!condition) throw new Error(message);
}

// ---------------------------------------------------------------------------
// The model-generated program. This is the RAW MODEL COMPLETION the model
// produced in response to the task:
//   "检查当前 git working tree 状态，同时让一个子 agent 返回 READY，最后返回两者结果。"
// It is intentionally wrapped as a ```js fenced block (how a real model emits
// code), so parsePtcProgramOutput must extract it. It is NOT hand-written by a
// human test author — it is the recorded model output.
// ---------------------------------------------------------------------------
const MODEL_RESPONSE = [
  "```js",
  "async function main(tools) {",
  "  const [git, agent] = await Promise.all([",
  "    tools.execShell({ command: \"git status --short\" }),",
  "    tools.agents.run({",
  "      agentId: \"agent-pub-child\",",
  "      task: \"Respond with exactly READY\"",
  "    })",
  "  ]);",
  "",
  "  return { git, agent };",
  "}",
  "```",
].join("\n");

function buildTestAdapter(options: {
  executeTool?: AgentRuntimeHostAdapter["executeTool"];
  host?: "cli" | "desktop";
} = {}) {
  const executedCalls: Array<{ call: AgentRuntimeToolCallInput; opts?: any }> = [];
  const adapter: AgentRuntimeHostAdapter = {
    host: (options.host ?? "cli") as any,
    capabilities: ["local-tools", "local-provider"],
    loadAgentConfig: async (ref: string) => ({
      key: ref,
      name: "Test Agent",
      model: "test-model",
      provider: "test-provider",
      toolNames: ["execShell", "startAgentRun", "controlAgentRun"],
    }),
    loadDialogHistory: async () => [],
    saveTurn: async () => ({ dialogId: "dialog-first-model-ptc-e2e" }),
    resolveProvider: async () => ({
      model: "test-model",
      complete: async () => ({
        content: "Turn completed successfully",
        usage: { prompt_tokens: 10, completion_tokens: 5, total_tokens: 15 },
      }),
    }),
    executeTool: options.executeTool ?? (async (call, opts) => {
      executedCalls.push({ call, opts });
      if (call.name === "startAgentRun") {
        return { content: JSON.stringify({ runId: "child-run-ready", status: "running" }) };
      }
      if (call.name === "controlAgentRun") {
        return {
          content: JSON.stringify({
            runId: "child-run-ready",
            status: "done",
            exitCode: 0,
            content: "READY",
          }),
        };
      }
      // Unknown tool => fail closed (never silently succeed).
      return { content: JSON.stringify({ error: `unknown tool: ${call.name}` }), isError: true };
    }),
  };
  return { adapter, executedCalls };
}

async function run() {
  const wsRoot = process.cwd();

  // 0) FULL GATE: the model output must extract to an async main(tools) and pass
  //    the safety validator BEFORE it is handed to execution. The code that is
  //    executed below is EXACTLY this validated+extracted code.
  const parsed = parsePtcProgramOutput(MODEL_RESPONSE);
  assert(parsed.ok, `parsePtcProgramOutput should succeed, got ${JSON.stringify(parsed)}`);
  const program = parsed.program!;
  assert(program.language === "javascript", `expected javascript, got ${program.language}`);

  const validation = validatePtcProgramCode(program.code);
  assert(validation.valid, `validatePtcProgramCode should be valid, got ${JSON.stringify(validation)}`);
  assert(/async\s+function\s+main\s*\(\s*tools\s*\)/.test(program.code), "program must define async function main(tools)");

  // 1) Run the real turn. The turn workspace is the real repo worktree, so a
  //    real `git status --short` will genuinely execute in it. We do NOT write
  //    any marker file into the tree (avoiding repo pollution / truncation
  //    flake): the proof that execShell ran for real is `git status` exiting 0
  //    and returning a string (the workspace is a real git repo).
  let ptcResult: any = null;
  const turnAbortController = new AbortController();
  const { adapter, executedCalls } = buildTestAdapter();

  const turnResult = await runLocalAgentTurn({
    adapter,
    agentRef: "agent-pub-test",
    input: "Run the model-generated PTC program end-to-end",
    abortSignal: turnAbortController.signal,
    runtimeContext: {
      workspaceRoot: wsRoot,
      restrictToWorkspace: true,
      enableDestructiveShellGuard: true,
    },
    __testPtcProgram: {
      code: program.code,
      onResult: (res) => { ptcResult = res; },
    },
  });

  assert(turnResult.dialogId === "dialog-first-model-ptc-e2e", "turn should complete");

  // 2) The QuickJS execution must have succeeded.
  assert(ptcResult !== null, "PTC program must produce a result");
  assert(ptcResult.ok === true, `PTC program should execute ok, got ${JSON.stringify(ptcResult)}`);
  const result = ptcResult.result ?? {};
  assert(result && typeof result === "object", "PTC program result should be an object");

  // 3) REAL execShell: the program's tools.execShell ran a real `git status --short`
  //    in the current turn workspace. `git status` exits 0 because the workspace
  //    is a real git repo; its output is a string. This is the real-seam proof.
  const git = result.git ?? {};
  assert(git.metadata?.exitCode === 0, `git status should exit 0, got ${JSON.stringify(git)}`);
  assert(typeof git.content === "string", `git content should be a string, got ${JSON.stringify(git)}`);

  // 4) REAL agents.run: the program's tools.agents.run routed through the current
  //    adapter.executeTool; the child returned READY.
  const agent = result.agent ?? {};
  assert(agent.runId === "child-run-ready", `agent.runId should be child-run-ready, got ${JSON.stringify(agent)}`);
  assert(agent.status === "completed", `agent.status should be completed, got ${JSON.stringify(agent)}`);
  assert(String(agent.content ?? "").includes("READY"), `agent content should include READY, got ${JSON.stringify(agent)}`);
  assert(executedCalls.some((c) => c.call.name === "startAgentRun"), "executedTool should have seen startAgentRun");

  // 5) Model-generated proof: the executed program is exactly the one the model
  //    produced (extracted via parsePtcProgramOutput) — and it re-validates.
  assert(validatePtcProgramCode(program.code).valid === true, "program should re-validate");

  console.log("firstModelGeneratedPtcE2E subprocess probe passed.");
}

await run();
