#!/usr/bin/env bun
/**
 * 部署后探测：确认线上每个路由级样式产物可访问、非空、且为本仓库生成的版本。
 * 由 runAlphaServerCi.sh 的 verify-alpha-health / verify-main-public-health 调用，
 * 防止「构建绿灯但 public/route-styles/*.css 线上 404 或陈旧」静默发布。
 *
 * 用法: bun scripts/verify/verifyDeployedRouteStyles.ts --base-url https://us.nolo.chat
 */
import { ROUTE_STYLE_OUTPUT_NAMES } from "../dev/routeStyles.js";

const parseBaseUrl = (argv: string[]): string => {
  const index = argv.indexOf("--base-url");
  const value = index >= 0 ? argv[index + 1] : undefined;
  if (!value) {
    console.error("❌ 缺少 --base-url <url> 参数");
    process.exit(2);
  }
  return value.replace(/\/+$/, "");
};

const baseUrl = parseBaseUrl(process.argv.slice(2));
const GENERATED_MARKER = "GENERATED by scripts/dev/routeStyles.js";
const FETCH_TIMEOUT_MS = 10_000;

let failures = 0;

for (const name of ROUTE_STYLE_OUTPUT_NAMES) {
  const url = `${baseUrl}/public/route-styles/${name}`;
  try {
    const response = await fetch(url, {
      signal: AbortSignal.timeout(FETCH_TIMEOUT_MS),
    });
    const body = await response.text();
    if (response.status !== 200) {
      console.error(`❌ ${url} -> HTTP ${response.status}`);
      failures += 1;
      continue;
    }
    if (body.length === 0) {
      console.error(`❌ ${url} -> 空响应体`);
      failures += 1;
      continue;
    }
    if (!body.includes(GENERATED_MARKER)) {
      console.error(`❌ ${url} -> 缺少 GENERATED 标记（可能是陈旧/手写产物）`);
      failures += 1;
      continue;
    }
    console.log(`✅ ${url} -> 200, ${body.length} bytes`);
  } catch (error) {
    console.error(`❌ ${url} -> 请求失败:`, error);
    failures += 1;
  }
}

if (failures > 0) {
  console.error(`❌ route-styles 部署探测失败: ${failures}/${ROUTE_STYLE_OUTPUT_NAMES.length} 个产物不可用`);
  process.exit(1);
}
console.log(`✅ 全部 ${ROUTE_STYLE_OUTPUT_NAMES.length} 个 route-styles 产物线上可访问`);
