#!/usr/bin/env bash

set -Eeuo pipefail

HOSTS="${NOLO_CADDY_HOSTS:?NOLO_CADDY_HOSTS is required, for example nolo.chat or us.nolo.chat}"
UPSTREAM_HOST="${NOLO_CADDY_UPSTREAM_HOST:-127.0.0.1}"
UPSTREAM_PORT="${NOLO_CADDY_UPSTREAM_PORT:-38123}"
CADDY_BIN="${NOLO_CADDY_BIN:-caddy}"
CADDYFILE_PATH="${NOLO_CADDYFILE_PATH:-/etc/caddy/Caddyfile}"
INSTALL_CADDY="${NOLO_CADDY_INSTALL:-1}"
PLATFORM_TLS_CERT="${NOLO_CADDY_PLATFORM_TLS_CERT:-}"
PLATFORM_TLS_KEY="${NOLO_CADDY_PLATFORM_TLS_KEY:-}"
PREVIEW_SLOTS="${NOLO_CADDY_PREVIEW_SLOTS:-}"
EXTRA_PROXY_FILE="${NOLO_CADDY_EXTRA_PROXY_FILE:-/etc/caddy/nolo-extra-proxy.caddy}"

run_root() {
  if [[ "$(id -u)" == "0" ]]; then
    "$@"
  else
    sudo "$@"
  fi
}

restore_tmp_runtime_state() {
  run_root install -d -m 1777 /tmp
  run_root chmod 1777 /tmp
}

ensure_caddy() {
  if command -v "$CADDY_BIN" >/dev/null 2>&1; then
    return
  fi

  if [[ "$INSTALL_CADDY" != "1" ]]; then
    echo "❌ caddy is not installed and NOLO_CADDY_INSTALL is not 1"
    exit 1
  fi

  if ! command -v apt-get >/dev/null 2>&1; then
    echo "❌ automatic Caddy install currently supports apt-get hosts only"
    exit 1
  fi

  run_root apt-get update
  run_root apt-get install -y caddy
}

normalize_hosts() {
  printf '%s\n' "$HOSTS" | tr ',' ' ' | xargs
}

caddy_site_addresses() {
  normalize_hosts | sed 's/ /, /g'
}

hosts_contain_wildcard() {
  local host
  for host in $(normalize_hosts); do
    if [[ "$host" == \*.* ]]; then
      return 0
    fi
  done
  return 1
}

normalize_preview_slots() {
  printf '%s\n' "$PREVIEW_SLOTS" | tr ',' ' ' | xargs
}

preview_slot_site_blocks() {
  local tls_block="$1"
  local entry host port

  for entry in $(normalize_preview_slots); do
    host="${entry%%:*}"
    port="${entry##*:}"
    if [[ -z "$host" || -z "$port" || "$host" == "$port" ]]; then
      echo "❌ invalid NOLO_CADDY_PREVIEW_SLOTS entry: ${entry} (expected host:port)"
      exit 1
    fi
    if ! [[ "$port" =~ ^[0-9]+$ ]]; then
      echo "❌ invalid preview port for ${host}: ${port}"
      exit 1
    fi
    cat <<EOF
${host} {
${tls_block}
	import nolo_proxy ${UPSTREAM_HOST} ${port}
}

EOF
  done
}

read_extra_proxy_snippet() {
  if [[ -f "$EXTRA_PROXY_FILE" ]]; then
    cat "$EXTRA_PROXY_FILE"
  fi
}

caddy_is_active() {
  if command -v systemctl >/dev/null 2>&1; then
    run_root systemctl is-active --quiet caddy
    return
  fi

  return 1
}

render_caddyfile() {
  local normalized_hosts
  normalized_hosts="$(normalize_hosts)"
  if [[ -z "$normalized_hosts" ]]; then
    echo "❌ NOLO_CADDY_HOSTS resolved to an empty host list"
    exit 1
  fi

  if hosts_contain_wildcard && { [[ -z "$PLATFORM_TLS_CERT" ]] || [[ -z "$PLATFORM_TLS_KEY" ]]; }; then
    echo "❌ wildcard platform hosts require NOLO_CADDY_PLATFORM_TLS_CERT and NOLO_CADDY_PLATFORM_TLS_KEY"
    echo "   Use a Cloudflare Origin Certificate or another wildcard certificate for *.nolo.chat."
    exit 1
  fi

  local site_addresses
  site_addresses="$(caddy_site_addresses)"

  local platform_tls_block=""
  if [[ -n "$PLATFORM_TLS_CERT" || -n "$PLATFORM_TLS_KEY" ]]; then
    if [[ -z "$PLATFORM_TLS_CERT" || -z "$PLATFORM_TLS_KEY" ]]; then
      echo "❌ NOLO_CADDY_PLATFORM_TLS_CERT and NOLO_CADDY_PLATFORM_TLS_KEY must be set together"
      exit 1
    fi
    platform_tls_block=$'\ttls '"${PLATFORM_TLS_CERT}"$' '"${PLATFORM_TLS_KEY}"
  fi

  local preview_site_blocks
  preview_site_blocks="$(preview_slot_site_blocks "$platform_tls_block")"

  local extra_proxy_snippet=""
  extra_proxy_snippet="$(read_extra_proxy_snippet)"

  cat <<EOF
# Generated by scripts/release/configureCaddyProxy.sh.
# Caddy owns public 80/443; Bun stays on the loopback upstream below.
{
	servers {
		protocols h1 h2
	}
	on_demand_tls {
		ask http://${UPSTREAM_HOST}:${UPSTREAM_PORT}/api/app/domain/allow
	}
}

(nolo_proxy) {
	encode gzip

${extra_proxy_snippet}

	@stream path /api/events/* /api/notifications /api/agent/run /api/v1/chat /api/connector/ws
	reverse_proxy @stream {args.0}:{args.1} {
		lb_try_duration 60s
		lb_try_interval 250ms
		# Retry only safe page/event reads when the upstream is draining.
		lb_retry_match {
			method GET HEAD
		}
		header_up -X-Nolo-Client-IP
		header_up X-Nolo-Client-IP {remote_host}
		header_up X-Real-IP {remote_host}
		flush_interval -1
	}

	reverse_proxy {args.0}:{args.1} {
		lb_try_duration 60s
		lb_try_interval 250ms
		# Retry only safe page/event reads when the upstream is draining.
		lb_retry_match {
			method GET HEAD
		}
		header_up -X-Nolo-Client-IP
		header_up X-Nolo-Client-IP {remote_host}
		header_up X-Real-IP {remote_host}
	}
}

${site_addresses} {
${platform_tls_block}
	import nolo_proxy ${UPSTREAM_HOST} ${UPSTREAM_PORT}
}

${preview_site_blocks}
https:// {
	tls {
		on_demand
	}
	import nolo_proxy ${UPSTREAM_HOST} ${UPSTREAM_PORT}
}

http:// {
	redir https://{host}{uri} 308
}
EOF
}

write_caddyfile_if_changed() {
  local tmp
  tmp="$(mktemp)"
  render_caddyfile > "$tmp"
  run_root "$CADDY_BIN" fmt --overwrite "$tmp"

  if run_root test -f "$CADDYFILE_PATH" && run_root cmp -s "$tmp" "$CADDYFILE_PATH" && caddy_is_active; then
    rm -f "$tmp"
    echo "✅ Caddy reverse proxy already current; skipping reload"
    return 1
  fi

  run_root install -d -m 755 "$(dirname "$CADDYFILE_PATH")"
  run_root install -m 644 "$tmp" "$CADDYFILE_PATH"
  rm -f "$tmp"
  return 0
}

reload_caddy() {
  run_root "$CADDY_BIN" validate --adapter caddyfile --config "$CADDYFILE_PATH"

  if command -v systemctl >/dev/null 2>&1; then
    run_root systemctl enable caddy
    if run_root systemctl is-active --quiet caddy; then
      if ! run_root systemctl reload caddy; then
        echo "⚠️ Caddy reload failed; showing service diagnostics before restart fallback"
        run_root systemctl status caddy --no-pager || true
        run_root journalctl -xeu caddy.service -n 80 --no-pager || true
        run_root systemctl restart caddy
      fi
    else
      run_root systemctl restart caddy
    fi
  else
    run_root "$CADDY_BIN" reload --adapter caddyfile --config "$CADDYFILE_PATH"
  fi
}

restore_tmp_runtime_state
ensure_caddy
if write_caddyfile_if_changed; then
  reload_caddy
fi

echo "✅ Caddy reverse proxy configured: hosts=$(normalize_hosts) upstream=${UPSTREAM_HOST}:${UPSTREAM_PORT}"
