/**
 * 单条 run 的面板渲染（composer 上方那两行执行者状态）。
 *
 * 从 activityIndicator.ts 移过来独立成模块，纯粹是为了断开 import 环：
 * activityIndicator 现在把面板状态托管给 runDock，而 runDock 单 run 时仍复用
 * 这个格式化函数。
 */

import { formatCreditsChip } from "../client/tokenUsage";
import type { AgentRunSnapshot } from "../client/agentRunSnapshot";
import {
  getAgentRunStatusIcon,
  runShowsLogTail,
} from "../../ai/tools/agent/agentRunDisplayHelpers";
import { activeInFlight, formatInFlightFact, formatTerminalRunAge, formatUnassignedFact, runStatusTone } from "./runSnapshotDisplay";
import { themeText } from "./theme";

/**
 * Progress suffix: ` · 12 tools · read, grep`. Empty when the run has not
 * reported any tool activity yet.
 */
function formatPanelProgress(snapshot: AgentRunSnapshot, now: number): string {
  const parts: string[] = [];
  if (typeof snapshot.toolCallCount === "number" && Number.isFinite(snapshot.toolCallCount)) {
    parts.push(`${snapshot.toolCallCount} tools`);
  }
  // 「此刻在做什么」压过「最后做过什么」——前者带自己的计时，看得出卡没卡住；
  // 后者只是历史。只有本地 registry 轮询报得出它。
  const inFlight = activeInFlight(snapshot);
  if (inFlight) {
    parts.push(formatInFlightFact(inFlight, now));
  } else if (snapshot.lastToolNames && snapshot.lastToolNames.length > 0) {
    parts.push(snapshot.lastToolNames.join(", "));
  }
  return parts.length > 0 ? ` · ${parts.join(" · ")}` : "";
}

/**
 * The run's own words beat its stdout. `lastAssistantText` is a sentence the
 * sub-agent wrote; the log tail is whatever byte sequence happened to land last
 * and is regularly a truncated JSON fragment.
 */
function formatPanelDetail(snapshot: AgentRunSnapshot): string {
  const note = snapshot.lastAssistantText?.trim();
  if (note) return note;
  // The log fallback obeys the same rule as the cards (`runShowsLogTail`)
  // rather than a second one of its own: raw stdout is evidence on a failed run
  // and noise on a healthy one.
  if (!runShowsLogTail(snapshot.status)) return "";
  const lines = snapshot.logLines;
  if (!lines || lines.length === 0) return "";
  return lines[lines.length - 1]?.trim() ?? "";
}

/**
 * Internal run ids are useful diagnostics but poor primary UI. Prefer a real
 * agent name; auto-generated `agent-…` identities collapse to the stable
 * human label "Sub-agent". Detailed ids remain available in run cards/pro
 * output, just not in the dock's most prominent line.
 *
 * Exported because the multi-run dock row (`runDock.formatRunDockRow`) shows
 * the same identity in the same panel: collapsing only the single-run form
 * would put the raw generated id back on screen as soon as a second run docks.
 */
/**
 * Auto-generated identities that must never own the dock's primary line:
 *  - the private agent key `agent-<accountId>-<id|slug>`; the account id is the
 *    10-char hex slice produced by `generateUserIdV1`;
 *  - the public key form `agent-pub-<id>`;
 *  - run ids (`run-<ISO>-<rand>`, see `defaultGenerateRunId`), which the run
 *    label resolver can hand back when a record carries no name at all.
 * A human-authored display name has none of these shapes: `agent-security-check`
 * stays visible because its first segment is not an account id.
 */
const AUTO_IDENTITY_PATTERNS: readonly RegExp[] = [
  /^agent-[0-9a-f]{8,}-[a-z0-9]/i,
  /^agent-pub-[a-z0-9]{10,}$/i,
  /^run-\d{4}-\d{2}-\d{2}T[\d-]+Z-[a-z0-9]+$/i,
];

function isAutoGeneratedIdentity(raw: string): boolean {
  return AUTO_IDENTITY_PATTERNS.some((pattern) => pattern.test(raw));
}

export function displayAgentName(snapshot: AgentRunSnapshot): string {
  const raw = snapshot.agentName?.trim();
  if (!raw) return "Sub-agent";
  if (isAutoGeneratedIdentity(raw)) return "Sub-agent";
  return raw;
}

export function formatAgentRunPanelLines(
  snapshot: AgentRunSnapshot,
  colorEnabled: boolean,
  now: number = Date.now()
): string[] {
  const lines: string[] = [];
  const name = displayAgentName(snapshot);
  const status = snapshot.status || "running";

  // Status vocabulary comes from the run store (`done`/`failed`/`timeout`/
  // `killed`/`cancelled`), not from a guessed list.
  const statusSymbol = getAgentRunStatusIcon(status);
  const statusColor = runStatusTone(status);

  const errPart = snapshot.errorMessage ? ` · ${snapshot.errorMessage}` : "";
  const unassignedFact = formatUnassignedFact(snapshot);
  const unassignedPart = unassignedFact ? ` · ${unassignedFact}` : "";
  const progressPart = formatPanelProgress(snapshot, now);
  const age = formatTerminalRunAge(snapshot, now);
  const agePart = age ? ` · ${age}` : "";
  const creditsPart =
    typeof snapshot.credits === "number" && Number.isFinite(snapshot.credits)
      ? ` · ${formatCreditsChip(snapshot.credits)}`
      : "";

  if (!colorEnabled) {
    lines.push(
      `🤖 ${name} · ${statusSymbol} ${status}${unassignedPart}${agePart}${progressPart}${creditsPart}${errPart}`
    );
  } else {
    const botIcon = themeText("🤖", "accent", true);
    const nameText = themeText(` ${name}`, "chrome", true);
    const statusText = themeText(` · ${statusSymbol} ${status}`, statusColor, true);
    const unassignedText = unassignedPart ? themeText(unassignedPart, "muted") : "";
    const ageText = agePart ? themeText(agePart, "chrome") : "";
    const progressText = progressPart ? themeText(progressPart, "chrome") : "";
    const creditsText = creditsPart ? themeText(creditsPart, "muted") : "";
    const errorText = errPart ? themeText(errPart, "danger") : "";
    lines.push(`${botIcon}${nameText}${statusText}${unassignedText}${ageText}${progressText}${creditsText}${errorText}`);
  }

  const detail = formatPanelDetail(snapshot);
  if (detail) {
    if (!colorEnabled) {
      lines.push(`   └ ${detail}`);
    } else {
      lines.push(`${themeText("   └ ", "muted")}${themeText(detail, "chrome")}`);
    }
  }

  return lines;
}
