import * as stylex from "@stylexjs/stylex";

export const agentPublishDialogStyles = stylex.create({
  layout: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) 300px",
    alignItems: "start",
    gap: "var(--space-7, 28px)",
    "@media (max-width: 760px)": {
      gridTemplateColumns: "1fr",
      gap: "var(--space-5)",
    },
  },
  formColumn: {
    display: "flex",
    flexDirection: "column",
    gap: "var(--space-6)",
    minWidth: 0,
  },
  section: {
    padding: 0,
    borderWidth: 0,
    backgroundColor: "transparent",
  },
  sectionDivider: {
    paddingTop: "var(--space-6)",
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: "var(--borderLight, var(--border))",
  },
  sectionHeading: {
    display: "flex",
    alignItems: "flex-start",
    gap: "var(--space-3)",
    marginBottom: "var(--space-4)",
  },
  sectionIcon: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    flex: "0 0 auto",
    width: "24px",
    height: "24px",
    borderRadius: "var(--radius-sm)",
    color: "var(--textSecondary)",
  },
  headingTitle: {
    margin: "0 0 2px",
    color: "var(--text)",
    fontSize: "var(--fontSize-base)",
    fontWeight: 650,
  },
  headingSubtitle: {
    margin: 0,
    color: "var(--textTertiary)",
    fontSize: "var(--fontSize-sm)",
    lineHeight: 1.5,
  },
  statusCard: {
    display: "grid",
    gridTemplateColumns: "auto minmax(0, 1fr) auto",
    alignItems: "center",
    gap: "var(--space-4)",
    padding: "var(--space-4)",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "var(--borderLight, var(--border))",
    borderRadius: "var(--radius-md, 10px)",
    backgroundColor: "var(--backgroundSecondary)",
    transitionProperty: "border-color",
    transitionDuration: "0.2s",
    transitionTimingFunction: "ease",
    "@media (max-width: 520px)": {
      gridTemplateColumns: "auto minmax(0, 1fr)",
    },
  },
  statusIcon: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    flex: "0 0 auto",
    width: "40px",
    height: "40px",
    borderRadius: "50%",
    backgroundColor: "var(--background)",
  },
  statusIconPublic: {
    color: "var(--success)",
  },
  statusIconPrivate: {
    color: "var(--textSecondary)",
  },
  statusCopy: {
    display: "flex",
    flexDirection: "column",
    gap: "2px",
    minWidth: 0,
  },
  statusCopyStrong: {
    color: "var(--text)",
    fontSize: "var(--fontSize-base)",
    fontWeight: 650,
  },
  statusCopySpan: {
    color: "var(--textTertiary)",
    fontSize: "var(--fontSize-sm)",
    lineHeight: 1.5,
  },
  runtimeNote: {
    display: "flex",
    alignItems: "flex-start",
    gap: "var(--space-2)",
    marginTop: "var(--space-3)",
    padding: "0 var(--space-1)",
    color: "var(--warning)",
    fontSize: "var(--fontSize-sm)",
    lineHeight: 1.6,
  },
  runtimeNoteSvg: {
    flexShrink: 0,
    marginTop: "3px",
  },
  runtimeNoteSpan: {
    color: "var(--textSecondary)",
  },
  priceGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: "var(--space-4)",
    "@media (max-width: 760px)": {
      gridTemplateColumns: "1fr",
    },
  },
  side: {
    position: "sticky",
    top: 0,
    display: "flex",
    flexDirection: "column",
    gap: "var(--space-6)",
    minWidth: 0,
    "@media (max-width: 760px)": {
      position: "static",
      paddingTop: "var(--space-5)",
      borderTopWidth: "1px",
      borderTopStyle: "solid",
      borderTopColor: "var(--borderLight, var(--border))",
    },
  },
  preview: {
    display: "flex",
    flexDirection: "column",
    gap: "var(--space-3)",
  },
  previewLabel: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    color: "var(--textTertiary)",
    fontSize: "var(--fontSize-xs)",
    fontWeight: 600,
    letterSpacing: "0.03em",
  },
  previewCard: {
    display: "flex",
    flexDirection: "column",
    gap: "var(--space-3)",
    padding: "var(--space-4)",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "var(--borderLight, var(--border))",
    borderRadius: "var(--radius-lg, 14px)",
    backgroundColor: "var(--backgroundSecondary)",
    transitionProperty: "opacity",
    transitionDuration: "0.2s",
    transitionTimingFunction: "ease",
  },
  previewCardDimmed: {
    opacity: 0.55,
  },
  previewHead: {
    display: "flex",
    alignItems: "center",
    gap: "var(--space-3)",
    minWidth: 0,
  },
  previewTitle: {
    display: "flex",
    flexDirection: "column",
    gap: "3px",
    minWidth: 0,
  },
  previewTitleStrong: {
    color: "var(--text)",
    fontSize: "var(--fontSize-sm)",
    fontWeight: 650,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  previewPrice: {
    alignSelf: "flex-start",
    padding: "1px 8px",
    borderRadius: "var(--radius-full, 999px)",
    backgroundColor: "var(--primaryGhost)",
    color: "var(--primary)",
    fontSize: "11px",
    fontWeight: 600,
    lineHeight: 1.6,
    whiteSpace: "nowrap",
  },
  previewIntro: {
    margin: 0,
    color: "var(--textSecondary)",
    fontSize: "12px",
    lineHeight: 1.7,
    display: "-webkit-box",
    WebkitLineClamp: 3,
    WebkitBoxOrient: "vertical",
    overflow: "hidden",
    minHeight: "3.4em",
  },
  previewCta: {
    alignSelf: "flex-end",
    display: "inline-flex",
    alignItems: "center",
    gap: "5px",
    padding: "5px 14px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "var(--borderLight, var(--border))",
    borderRadius: "var(--radius-full, 999px)",
    color: "var(--primary)",
    fontSize: "12px",
    fontWeight: 600,
  },
  previewHint: {
    margin: 0,
    color: "var(--textTertiary)",
    fontSize: "var(--fontSize-xs)",
    lineHeight: 1.5,
  },
  preflight: {
    paddingTop: "var(--space-5)",
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: "var(--borderLight, var(--border))",
  },
  preflightHeading: {
    display: "flex",
    alignItems: "flex-start",
    gap: "var(--space-3)",
    marginBottom: "var(--space-2)",
  },
  checkList: {
    display: "flex",
    flexDirection: "column",
  },
  check: {
    display: "grid",
    gridTemplateColumns: "auto minmax(0, 1fr)",
    gap: "var(--space-3)",
    padding: "var(--space-3) 0",
  },
  checkIcon: {
    marginTop: "1px",
  },
  checkIconPassed: {
    color: "var(--success)",
  },
  checkIconPending: {
    color: "var(--warning)",
  },
  checkContent: {
    display: "flex",
    flexDirection: "column",
    gap: "2px",
  },
  checkStrong: {
    color: "var(--text)",
    fontSize: "var(--fontSize-sm)",
    fontWeight: 600,
  },
  checkSpan: {
    color: "var(--textTertiary)",
    fontSize: "var(--fontSize-xs)",
    lineHeight: 1.5,
  },
  summary: {
    display: "flex",
    flexDirection: "column",
    gap: "4px",
    marginTop: "var(--space-3)",
    padding: "var(--space-3) var(--space-4)",
    borderRadius: "var(--radius-md, 10px)",
    backgroundColor: "var(--backgroundSecondary)",
  },
  summaryStrong: {
    color: "var(--text)",
    fontSize: "var(--fontSize-sm)",
    fontWeight: 600,
  },
  summaryStrongReady: {
    color: "var(--success)",
  },
  summarySpan: {
    color: "var(--textTertiary)",
    fontSize: "var(--fontSize-xs)",
    lineHeight: 1.5,
  },
  footerNote: {
    color: "var(--textTertiary)",
    fontSize: "var(--fontSize-xs)",
    "@media (max-width: 760px)": {
      display: "none",
    },
  },
  footerActions: {
    display: "flex",
    alignItems: "center",
    gap: "var(--space-2)",
  },
});
