import * as stylex from "@stylexjs/stylex";

export const agentPageStyles = stylex.create({
  page: {
    boxSizing: "border-box",
    width: "100%",
    padding: "var(--space-5) var(--space-4)",
    maxWidth: "1040px",
    margin: "0 auto",
    "@media (max-width: 768px)": {
      padding: "var(--space-4) var(--space-2)",
    },
  },
  container: {
    backgroundColor: "transparent",
    borderRadius: "var(--radius-md)",
    padding: "var(--space-5) var(--space-6)",
    display: "flex",
    flexDirection: "column",
    gap: "var(--space-6)",
    borderWidth: 0,
    "@media (max-width: 768px)": {
      padding: "var(--space-4) var(--space-3)",
      gap: "var(--space-5)",
      borderRadius: 0,
      borderWidth: 0,
      backgroundColor: "transparent",
    },
  },
  layout: {
    display: "flex",
    gap: "var(--space-5, 20px)",
    alignItems: "flex-start",
    width: "100%",
    "@media (max-width: 768px)": {
      flexDirection: "column",
      gap: "var(--space-5)",
    },
  },
  main: {
    flex: 1,
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
    gap: "var(--space-4, 16px)",
  },
  sidebar: {
    width: "clamp(260px, 30%, 304px)",
    flexShrink: 0,
    display: "flex",
    flexDirection: "column",
    gap: "var(--space-5, 20px)",
    maxHeight: "calc(100vh - 180px)",
    overflowY: "auto",
    paddingRight: "2px",
    "@media (max-width: 768px)": {
      width: "100%",
      maxHeight: "none",
      overflow: "visible",
      backgroundColor: "transparent",
      borderWidth: 0,
      padding: 0,
    },
  },
  header: {
    display: "flex",
    flexDirection: "column",
    gap: "var(--space-4)",
    position: "relative",
    padding: "var(--space-4) 0 var(--space-5)",
    backgroundColor: "transparent",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: "var(--borderLight, var(--border))",
    boxShadow: "none",
    overflow: "hidden",
    transitionProperty: "border-color",
    transitionDuration: "0.2s",
    transitionTimingFunction: "ease",
    "@media (max-width: 768px)": {
      flexDirection: "column",
      alignItems: "center",
      textAlign: "center",
      gap: "var(--space-3)",
    },
  },
  headerTop: {
    display: "flex",
    gap: "var(--space-4)",
    alignItems: "flex-start",
    width: "100%",
  },
  avatar: {
    width: "60px",
    height: "60px",
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "14px",
    backgroundColor: "var(--backgroundSecondary)",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "var(--borderLight)",
    overflow: "hidden",
    boxShadow: "0 2px 6px rgba(0, 0, 0, 0.04)",
    transitionProperty: "transform",
    transitionDuration: "0.2s",
    transitionTimingFunction: "ease",
    "@media (max-width: 768px)": {
      width: "56px",
      height: "56px",
    },
  },
  headerActionsTop: {
    display: "flex",
    alignItems: "center",
    gap: "var(--space-2)",
    marginLeft: "auto",
    flexShrink: 0,
  },
  favBtn: {
    position: "static",
    ":active": {
      transform: "scale(0.9)",
    },
  },
  info: {
    flex: 1,
    minWidth: 0,
  },
  name: {
    fontSize: "1.45rem",
    margin: "0 0 var(--space-2)",
    fontWeight: 700,
    letterSpacing: "-0.02em",
    color: "var(--textHeading, var(--text))",
    lineHeight: 1.25,
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: "var(--space-2)",
    "@media (max-width: 768px)": {
      fontSize: "1.3rem",
    },
  },
  headerBadges: {
    display: "inline-flex",
    gap: "var(--space-2)",
    alignItems: "center",
    marginLeft: "var(--space-3)",
    verticalAlign: "middle",
  },
  headerBadge: {
    display: "inline-flex",
    alignItems: "center",
    gap: "var(--space-1)",
    padding: "var(--space-1) var(--space-2)",
    borderRadius: "var(--radius-full)",
    fontSize: "var(--fontSize-xs)",
    fontWeight: 500,
  },
  headerBadgePublic: {
    backgroundColor: "rgba(16, 185, 129, 0.1)",
    color: "var(--success, #10b981)",
  },
  headerBadgePrivate: {
    backgroundColor: "rgba(107, 114, 128, 0.1)",
    color: "var(--textTertiary)",
  },
  headerBadgeCli: {
    backgroundColor: "rgba(139, 92, 246, 0.1)",
    color: "#8b5cf6",
  },
  headerBadgeCustom: {
    backgroundColor: "rgba(245, 158, 11, 0.1)",
    color: "var(--warning, #f59e0b)",
  },
  headerBadgePlatform: {
    backgroundColor: "rgba(59, 130, 246, 0.1)",
    color: "#3b82f6",
  },
  description: {
    fontSize: "13.5px",
    lineHeight: 1.65,
    color: "var(--textSecondary)",
    margin: "var(--space-2) 0 var(--space-3)",
    whiteSpace: "pre-wrap",
    display: "-webkit-box",
    WebkitLineClamp: 3,
    WebkitBoxOrient: "vertical",
    overflow: "hidden",
    "@media (max-width: 768px)": {
      fontSize: "12px",
    },
  },
  descriptionFallback: {
    color: "var(--textTertiary)",
    fontStyle: "italic",
  },
  heroScenarios: {
    display: "flex",
    flexWrap: "wrap",
    gap: "6px",
    margin: "var(--space-2) 0 var(--space-3)",
  },
  heroChip: {
    display: "inline-flex",
    alignItems: "center",
    padding: "3px 10px",
    borderRadius: "var(--radius-full, 999px)",
    backgroundColor: "var(--primaryGhost, rgba(37, 99, 235, 0.1))",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "var(--borderLight, var(--border))",
    color: "var(--primary)",
    fontSize: "12px",
    fontWeight: 500,
  },
  meta: {
    display: "flex",
    gap: "var(--space-4)",
    flexWrap: "wrap",
    alignItems: "center",
    "@media (max-width: 768px)": {
      justifyContent: "center",
    },
  },
  metaItem: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    fontSize: "12px",
    color: "var(--textSecondary)",
  },
  metaLabel: {
    color: "var(--textTertiary)",
    fontWeight: 500,
  },
  metaValue: {
    minWidth: 0,
  },
  metaValueCreator: {
    display: "inline-flex",
    alignItems: "center",
  },
  creatorLink: {
    display: "inline-flex",
    alignItems: "center",
    gap: "5px",
    maxWidth: "100%",
    color: "var(--primary)",
    textDecoration: "none",
    fontWeight: 600,
    fontSize: "12px",
    ":hover": {
      opacity: 0.8,
    },
    "@media (max-width: 768px)": {
      fontSize: "12px",
    },
  },
  creatorName: {
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  modelValueContainer: {
    display: "inline-flex",
    alignItems: "center",
    gap: "5px",
    minWidth: 0,
  },
  modelName: {
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  visionBadge: {
    display: "inline-flex",
    alignItems: "center",
    gap: "2px",
    flexShrink: 0,
    height: "15px",
    padding: "0 4px",
    borderRadius: "var(--radius-full, 999px)",
    fontSize: "9px",
    fontWeight: 600,
    lineHeight: 1,
  },
  visionBadgeActive: {
    backgroundColor: "var(--primaryGhost)",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "var(--borderAccent, var(--border))",
    color: "var(--primary)",
  },
  visionBadgeInactive: {
    backgroundColor: "transparent",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "var(--borderLight)",
    color: "var(--textTertiary)",
    opacity: 0.55,
  },
  heroCtaRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "var(--space-4)",
    paddingTop: "var(--space-4)",
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: "var(--borderLight, var(--border))",
    marginTop: "var(--space-2)",
    "@media (max-width: 640px)": {
      flexDirection: "column",
      alignItems: "stretch",
      gap: "var(--space-3)",
    },
  },
  adminActions: {
    display: "flex",
    alignItems: "center",
    gap: "var(--space-2)",
    "@media (max-width: 640px)": {
      display: "grid",
      gridTemplateColumns: "repeat(2, 1fr)",
      width: "100%",
    },
    "@media (max-width: 480px)": {
      gridTemplateColumns: "1fr",
    },
  },
  content: {
    display: "flex",
    flexDirection: "column",
    gap: "var(--space-5)",
    minHeight: "280px",
  },
  section: {
    display: "flex",
    flexDirection: "column",
    gap: "var(--space-3)",
    padding: 0,
    backgroundColor: "transparent",
    borderWidth: 0,
  },
  bodyPlaceholder: {
    minHeight: "280px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  sectionAbilityProof: {
    minHeight: "120px",
    padding: 0,
  },
  sectionDescription: {
    padding: 0,
  },
  chipRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: "var(--space-2)",
  },
  scenarioRow: {
    marginTop: "var(--space-2)",
  },
  chip: {
    display: "inline-flex",
    alignItems: "center",
    maxWidth: "100%",
    padding: "2px 10px",
    borderRadius: "var(--radius-full, 999px)",
    backgroundColor: "transparent",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: {
      default: "var(--borderLight, var(--border))",
      ":hover": "var(--primary)",
    },
    color: {
      default: "var(--textSecondary)",
      ":hover": "var(--primary)",
    },
    fontSize: "12px",
    fontWeight: 500,
    lineHeight: 1.6,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    transitionProperty: "all",
    transitionDuration: "0.2s",
    transitionTimingFunction: "ease",
  },
  chipMore: {
    color: "var(--textTertiary)",
    borderColor: "transparent",
    backgroundColor: "transparent",
  },
  chipGroup: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
    minWidth: 0,
    paddingTop: "var(--space-3)",
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: "var(--borderLight)",
  },
  chipGroupLabel: {
    color: "var(--textTertiary)",
    fontSize: "11px",
    fontWeight: 600,
    letterSpacing: "0.04em",
    textTransform: "uppercase",
  },
  abilityProofEmpty: {
    margin: 0,
    color: "var(--textTertiary)",
    fontSize: "12px",
    lineHeight: 1.6,
  },
  sectionPrompts: {
    gap: "var(--space-3)",
  },
  promptsTitle: {
    margin: 0,
    fontSize: "12px",
    fontWeight: 600,
    letterSpacing: "0.02em",
    color: "var(--textSecondary)",
  },
  promptGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: "var(--space-3)",
    "@media (max-width: 768px)": {
      gridTemplateColumns: "1fr",
    },
  },
  promptCard: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: "var(--space-3)",
    padding: "var(--space-3) var(--space-4)",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: {
      default: "var(--borderLight, var(--border))",
      ":hover": "var(--primary)",
    },
    borderRadius: "var(--radius-md, 10px)",
    backgroundColor: {
      default: "transparent",
      ":hover": "var(--backgroundHover)",
    },
    color: {
      default: "var(--textSecondary)",
      ":hover": "var(--text)",
    },
    font: "inherit",
    fontSize: "13px",
    lineHeight: 1.6,
    textAlign: "left",
    cursor: "pointer",
    transform: {
      default: null,
      ":hover": "translateY(-1px)",
    },
    transitionProperty: "all",
    transitionDuration: "0.2s",
    transitionTimingFunction: "ease",
  },
  promptCardDisabled: {
    cursor: "default",
    opacity: 0.6,
  },
  promptText: {
    minWidth: 0,
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical",
    overflow: "hidden",
  },
  promptIcon: {
    flexShrink: 0,
    marginTop: "3px",
    color: "var(--textTertiary)",
    opacity: 0.7,
    transitionProperty: "color, opacity",
    transitionDuration: "0.15s",
    transitionTimingFunction: "ease",
  },
  emptyState: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "var(--space-2)",
    padding: "var(--space-6) 0",
    textAlign: "center",
    color: "var(--textTertiary)",
  },
  emptyStateP: {
    margin: 0,
    fontSize: "var(--fontSize-sm)",
    color: "var(--textSecondary)",
  },
  emptyStateSpan: {
    fontSize: "12px",
    color: "var(--textTertiary)",
  },
  sectionEmailBinding: {
    padding: 0,
  },
  emailBinding: {
    display: "flex",
    flexDirection: "column",
    gap: "var(--space-3)",
    padding: 0,
    backgroundColor: "transparent",
    borderWidth: 0,
  },
  emailBindingHeading: {
    display: "flex",
    alignItems: "center",
    gap: "var(--space-2)",
    flexWrap: "wrap",
    fontSize: "13px",
    fontWeight: 600,
    color: "var(--text)",
  },
  emailBindingIntro: {
    margin: 0,
    color: "var(--textSecondary)",
    fontSize: "12px",
    lineHeight: 1.6,
  },
  emailBindingList: {
    margin: 0,
    padding: 0,
    listStyle: "none",
    display: "flex",
    flexDirection: "column",
    gap: "var(--space-3)",
  },
  emailBindingItem: {
    display: "flex",
    flexDirection: "column",
    gap: "2px",
    padding: "var(--space-2) var(--space-3)",
    borderRadius: "var(--radius-md, 8px)",
    backgroundColor: "var(--backgroundHover)",
    borderWidth: 0,
  },
  emailBindingAddress: {
    fontSize: "13px",
    fontWeight: 500,
    color: "var(--text)",
    wordBreak: "break-all",
  },
  emailBindingInboxLink: {
    marginLeft: "auto",
    display: "inline-flex",
    alignItems: "center",
    gap: "var(--space-1)",
    fontSize: "12px",
    fontWeight: 500,
    color: "var(--primary)",
    textDecoration: {
      default: "none",
      ":hover": "underline",
    },
  },
  emailBindingMeta: {
    fontSize: "11px",
    color: "var(--textSecondary)",
  },
  abilityProof: {
    display: "flex",
    flexDirection: "column",
    gap: "var(--space-4)",
    padding: 0,
    backgroundColor: "transparent",
    borderWidth: 0,
  },
  abilityProofHeading: {
    alignItems: "center",
    color: "var(--text)",
    display: "inline-flex",
    fontSize: "13px",
    fontWeight: 600,
    gap: "var(--space-2)",
  },
  abilityProofGrid: {
    display: "grid",
    gap: "var(--space-4)",
    gridTemplateColumns: "1fr",
    "@media (max-width: 768px)": {
      gridTemplateColumns: "1fr",
    },
  },
  abilityProofAdvanced: {
    color: "var(--textSecondary)",
    fontSize: "12px",
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: "var(--borderLight)",
    paddingTop: "var(--space-2)",
    marginTop: "2px",
  },
  abilityProofAdvancedSummary: {
    alignItems: "center",
    cursor: "pointer",
    display: "inline-flex",
    fontWeight: 600,
    gap: "6px",
    minHeight: "24px",
    color: {
      default: "var(--textSecondary)",
      ":hover": "var(--text)",
    },
    transitionProperty: "color",
    transitionDuration: "0.15s",
    transitionTimingFunction: "ease",
  },
  abilityProofStatus: {
    display: "flex",
    flexDirection: "column",
    gap: "5px",
    paddingTop: "6px",
  },
  abilityProofStatusTitle: {
    alignItems: "center",
    color: "var(--text)",
    display: "inline-flex",
    fontSize: "12px",
    fontWeight: 700,
    gap: "6px",
  },
  abilityProofStatusP: {
    color: "var(--textSecondary)",
    fontSize: "12px",
    lineHeight: 1.55,
    margin: 0,
  },
  runtimeEvidence: {
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: "var(--borderLight)",
    display: "flex",
    flexDirection: "column",
    gap: "6px",
    marginTop: "4px",
    paddingTop: "8px",
  },
  runtimeEvidenceTitle: {
    alignItems: "center",
    color: "var(--text)",
    display: "inline-flex",
    fontSize: "12px",
    fontWeight: 700,
    gap: "6px",
  },
  runtimeEvidenceSummary: {
    color: "var(--textSecondary)",
    fontSize: "12px",
    lineHeight: 1.5,
    margin: 0,
  },
  runtimeEvidenceGrid: {
    display: "grid",
    gap: "5px 10px",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    "@media (max-width: 768px)": {
      gridTemplateColumns: "1fr",
    },
  },
  runtimeEvidenceRow: {
    alignItems: "baseline",
    display: "flex",
    gap: "6px",
    minWidth: 0,
  },
  runtimeEvidenceRowSpan: {
    color: "var(--textTertiary)",
    flex: "0 0 auto",
    fontSize: "11px",
  },
  runtimeEvidenceRowStrong: {
    color: "var(--text)",
    fontSize: "12px",
    fontWeight: 600,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  runtimeEvidenceLink: {
    alignSelf: "flex-start",
    color: "var(--primary)",
    fontSize: "12px",
    fontWeight: 600,
    textDecoration: {
      default: "none",
      ":hover": "underline",
    },
  },
  sectionActivity: {
    gap: "var(--space-4)",
    padding: 0,
  },
  tabLabelWrap: {
    display: "flex",
    alignItems: "center",
    gap: "5px",
    minWidth: 0,
  },
  activityTabCount: {
    minWidth: "1.3em",
    height: "1.3em",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "0 0.25em",
    borderRadius: "999px",
    backgroundColor: "var(--backgroundSelected, var(--backgroundHover))",
    color: "currentColor",
    fontSize: "10px",
    lineHeight: 1,
    flexShrink: 0,
    marginLeft: "2px",
  },
  activityTabsNav: {
    width: "100%",
    marginBottom: "var(--space-4, 16px)",
  },
  activitySections: {
    display: "flex",
    flexDirection: "column",
    gap: "var(--space-5)",
    minHeight: "120px",
  },
  activitySectionHeader: {
    alignItems: "center",
    display: "flex",
    justifyContent: "space-between",
    gap: "var(--space-3)",
  },
  activitySectionTitle: {
    margin: 0,
    fontSize: "var(--font-size-xs, 0.75rem)",
    fontWeight: 600,
    letterSpacing: "0.02em",
    color: "var(--textSecondary)",
    textTransform: "none",
  },
  activityPanel: {
    minWidth: 0,
    maxHeight: "min(34vh, 320px)",
    overflowY: "auto",
    paddingRight: "var(--space-1)",
    "@media (max-width: 768px)": {
      maxHeight: "none",
      overflow: "visible",
      paddingRight: 0,
    },
  },
  historyList: {
    display: "flex",
    flexDirection: "column",
    marginTop: "var(--space-3)",
  },
  historyListManage: {
    maxHeight: "60vh",
    overflowY: "auto",
  },
  managePagination: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "var(--space-3)",
    marginTop: "var(--space-4)",
    paddingTop: "var(--space-3)",
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: "var(--border, rgba(0, 0, 0, 0.08))",
  },
  managePaginationInfo: {
    fontSize: "var(--font-size-sm, 13px)",
    color: "var(--text-secondary, #888)",
  },
  managePaginationButtons: {
    display: "flex",
    gap: "var(--space-2)",
  },
  historyItem: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "var(--space-4)",
    padding: "var(--space-3) var(--space-3)",
    textDecoration: "none",
    color: "inherit",
    borderRadius: "var(--radius-md, 8px)",
    backgroundColor: {
      default: "transparent",
      ":hover": "var(--backgroundHover)",
    },
    transform: {
      default: null,
      ":hover": "translateX(4px)",
    },
    transitionProperty: "background, transform",
    transitionDuration: "0.2s",
    transitionTimingFunction: "ease",
  },
  historyContent: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "baseline",
    flex: 1,
    minWidth: 0,
    gap: "var(--space-4)",
    textDecoration: "none",
  },
  historyDeleteBtn: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
    borderWidth: 0,
    color: "var(--textTertiary)",
    padding: "var(--space-1)",
    borderRadius: "var(--radius-sm, 6px)",
    cursor: "pointer",
    transitionProperty: "opacity, color, background",
    transitionDuration: "0.15s",
    transitionTimingFunction: "ease",
    marginLeft: "var(--space-2)",
    flexShrink: 0,
  },
  historyTitle: {
    fontSize: "var(--fontSize-sm)",
    fontWeight: 600,
    color: "var(--text)",
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  historyMeta: {
    flexShrink: 0,
    fontSize: "11px",
    fontWeight: 400,
    color: "var(--textTertiary)",
    whiteSpace: "nowrap",
  },
  historyEmpty: {
    padding: "var(--space-6) 0",
    textAlign: "center",
    color: "var(--textTertiary)",
    fontSize: "var(--fontSize-sm)",
  },
  threadList: {
    display: "flex",
    flexDirection: "column",
    gap: "var(--space-1)",
    marginTop: "var(--space-2)",
  },
  threadItem: {
    display: "flex",
    flexDirection: "column",
    gap: "2px",
    minWidth: 0,
    padding: "var(--space-3) var(--space-2)",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: "var(--borderLight)",
    color: "inherit",
    textDecoration: "none",
    backgroundColor: {
      default: "transparent",
      ":hover": "var(--backgroundHover)",
    },
    transitionProperty: "background, padding-left",
    transitionDuration: "0.15s",
    transitionTimingFunction: "ease",
  },
  threadTitle: {
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: "var(--fontSize-sm)",
    fontWeight: 500,
    color: "var(--text)",
  },
  threadMeta: {
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: "11px",
    fontWeight: 400,
    color: "var(--textTertiary)",
  },
  stateIndicator: {
    minHeight: "min(50vh, 360px)",
    alignItems: "center",
    justifyContent: "center",
    textAlign: "center",
    gap: "var(--space-4)",
    maxWidth: "420px",
    margin: "0 auto",
  },
  stateIndicatorH2: {
    margin: 0,
  },
  stateIndicatorP: {
    margin: 0,
    color: "var(--textSecondary)",
  },
});
