import * as stylex from "@stylexjs/stylex";

export const agentMemoryTabStyles = stylex.create({
  container: {
    display: "flex",
    flexDirection: "column",
  },
  header: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: "var(--space-4, 16px)",
    marginBottom: "var(--space-4, 16px)",
  },
  title: {
    margin: "0 0 4px",
    fontSize: "15px",
    fontWeight: 600,
    color: "var(--text)",
  },
  description: {
    margin: 0,
    fontSize: "13px",
    lineHeight: 1.6,
    color: "var(--textSecondary)",
  },
  actions: {
    display: "flex",
    alignItems: "center",
    gap: "var(--space-2, 8px)",
    flexShrink: 0,
  },
  spin: {
    animationName: "agent-memory-spin",
    animationDuration: "1s",
    animationTimingFunction: "linear",
    animationIterationCount: "infinite",
  },
  empty: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "var(--space-2, 8px)",
    padding: "var(--space-8, 32px) 0",
    color: "var(--textTertiary)",
    textAlign: "center",
  },
  truncatedHint: {
    margin: "0 0 var(--space-2, 8px)",
    fontSize: "12px",
    lineHeight: 1.5,
    color: "var(--textTertiary)",
  },
  list: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    display: "flex",
    flexDirection: "column",
    gap: "var(--space-2, 8px)",
  },
  item: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: "var(--space-3, 12px)",
    padding: "var(--space-3, 12px)",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "var(--border)",
    borderRadius: "10px",
    backgroundColor: "var(--backgroundSecondary)",
  },
  itemMain: {
    flex: 1,
    minWidth: 0,
  },
  itemContent: {
    fontSize: "14px",
    lineHeight: 1.6,
    color: "var(--text)",
    wordBreak: "break-word",
  },
  itemMeta: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: "var(--space-3, 12px)",
    marginTop: "var(--space-2, 8px)",
    fontSize: "12px",
    color: "var(--textTertiary)",
  },
  badge: {
    padding: "1px 8px",
    borderRadius: "999px",
    fontSize: "12px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "var(--border)",
    color: "var(--textSecondary)",
  },
  badgeSemantic: {
    borderColor: "var(--primary)",
    color: "var(--primary)",
  },
  add: {
    display: "flex",
    flexDirection: "column",
    gap: "var(--space-2, 8px)",
    marginBottom: "var(--space-4, 16px)",
    padding: "var(--space-3, 12px)",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "var(--border)",
    borderRadius: "10px",
    backgroundColor: "var(--backgroundSecondary)",
  },
  addInput: {
    width: "100%",
    resize: "vertical",
    minHeight: "48px",
    padding: "var(--space-2, 8px)",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "var(--border)",
    borderRadius: "8px",
    backgroundColor: "var(--background)",
    color: "var(--text)",
    fontSize: "14px",
    lineHeight: 1.6,
    fontFamily: "inherit",
    ":focus": {
      outline: "none",
      borderColor: "var(--primary)",
    },
  },
});
