#!/usr/bin/env bash
# syncNoloOpenSourceMirror.sh — 从 bun-nolo 生成公开镜像并推送到 nolotus/nolo。
#
# 用法：
#   ./scripts/ci/syncNoloOpenSourceMirror.sh
#
# 前提：
#   - 当前在 bun-nolo 仓库根目录
#   - 已安装 bun
#   - 有 nolotus/nolo 的 push 权限（gh auth 或 SSH key）
#
# 这个脚本做 3 件事：
# 1. 跑 prepareNoloOpenSourceMirror.ts 生成 mirror（含 safety gate 验证）
# 2. 在 mirror 里 git init + commit
# 3. force push 到 nolotus/nolo main 分支
#
# 快照式同步：无历史，每次都是干净树。等未来有外部贡献者再改 PR 流程。
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
PUBLIC_REPO="git@github.com:nolotus/nolo.git"
MIRROR_DIR="/tmp/nolo-open-source-mirror-push"

echo "🔍 1/3 生成公开镜像..."
cd "$REPO_ROOT"
rm -rf "$MIRROR_DIR"
bun scripts/release/prepareNoloOpenSourceMirror.ts --out-dir "$MIRROR_DIR"

echo "📦 2/3 初始化 git 并提交..."
cd "$MIRROR_DIR"
git init --quiet
git checkout -b main --quiet
git add -A
COMMIT_MSG="chore: sync open-source public projection $(date -u +%Y-%m-%d)

Generated by syncNoloOpenSourceMirror.sh from bun-nolo.
Projection gate: 0 violations (PASS).

Assistant-Model: glm-5.2
Assistant-Harness: nolo-tui"
git commit --quiet -m "$COMMIT_MSG"

FILE_COUNT=$(git ls-files | wc -l | tr -d ' ')
echo "   提交 $FILE_COUNT 个文件"

echo "🚀 3/3 推送到 nolotus/nolo..."
git remote add origin "$PUBLIC_REPO" 2>/dev/null || true
git push --force origin main

echo "✅ 完成！公共仓库已更新：https://github.com/nolotus/nolo"
echo "   CI 将自动触发：projection gate + build 验证"