#!/usr/bin/env bash
# syncNoloOpenSourceMirror.sh — 从 bun-nolo 生成公开镜像并追加同步到 nolotus/nolo。
#
# 用法：
#   ./scripts/ci/syncNoloOpenSourceMirror.sh            # 生成投影树并追加同步
#   ./scripts/ci/syncNoloOpenSourceMirror.sh --check    # 只读对账，不推送
#
# 前提：
#   - 当前在 bun-nolo 仓库根目录
#   - 已安装 bun
#   - 有 nolotus/nolo 的 push 权限（gh auth 或 SSH key）
#
# 这个脚本做 3 件事：
# 1. 跑 prepareNoloOpenSourceMirror.ts 生成 mirror（含 safety gate 验证）
# 2. 在 mirror 里 git init，以公开仓 main 当前 HEAD 为 parent 追加单个 commit
#    （append-only：绝不 force-push，兼容公开仓分支保护禁用 force-push）
# 3. fast-forward push 到 nolotus/nolo main 分支
#
# 远端分叉时 fetch --rebase 本地投影分支重试一次，仍失败则明确报错退出（非零）。
# commit message 首行固定 "chore: sync open-source public projection"，并追加
# Source-Commit / Source-Release-Tag 两个 trailer 供 audit 对账。
set -euo pipefail

REPO_ROOT="${SYNC_REPO_ROOT:-$(cd "$(dirname "$0")/../.." && pwd)}"
PUBLIC_REPO="${SYNC_PUBLIC_REPO:-git@github.com:nolotus/nolo.git}"
# CI 中无 SSH key：提供 SYNC_GH_TOKEN（或映射 CLI_MIRROR_GH_TOKEN）时改走
# https + token push；git 自身会 redact 输出中的凭据。
SYNC_GH_TOKEN="${SYNC_GH_TOKEN:-${CLI_MIRROR_GH_TOKEN:-}}"
if [ -n "$SYNC_GH_TOKEN" ]; then
  PUBLIC_REPO="https://x-access-token:${SYNC_GH_TOKEN}@github.com/nolotus/nolo.git"
fi
MIRROR_DIR="${SYNC_MIRROR_DIR:-/tmp/nolo-open-source-mirror-push}"
STAGE_DIR="${SYNC_STAGE_DIR:-/tmp/nolo-open-source-mirror-stage}"
PUBLIC_BRANCH="${SYNC_PUBLIC_BRANCH:-main}"

# 私有仓当前 HEAD（bot commit sha，写入 Source-Commit trailer）
SOURCE_COMMIT="$(git -C "$REPO_ROOT" rev-parse HEAD)"

# 最高可达组件 tag 列表（cli + desktop，按 version:refname 排序取最高）
source_release_tags() {
  local tags=""
  for prefix in cli-v desktop-v; do
    local t
    t="$(git -C "$REPO_ROOT" for-each-ref --merged=HEAD --sort=version:refname \
      --format='%(refname:short)' "refs/tags/${prefix}*" | tail -1 || true)"
    if [ -n "$t" ]; then
      tags="${tags:+$tags, }$t"
    fi
  done
  echo "$tags"
}

# 私有仓待投影的 cli 版本（packages/cli/package.json）
private_cli_version() {
  bun -e 'const p=require(process.argv[1]);process.stdout.write(p.version)' \
    "$REPO_ROOT/packages/cli/package.json"
}

# 公开仓 main 当前 cli 版本（只读，--check 用）
public_cli_version() {
  local tmp
  tmp="$(mktemp -d)"
  git clone --quiet --depth 1 --branch "$PUBLIC_BRANCH" "$PUBLIC_REPO" "$tmp" 2>/dev/null || {
    rm -rf "$tmp"
    return 1
  }
  local v
  v="$(bun -e 'const p=require(process.argv[1]);process.stdout.write(p.version)' \
    "$tmp/packages/cli/package.json" 2>/dev/null || true)"
  rm -rf "$tmp"
  echo "$v"
}

check_mode() {
  echo "🔍 --check 模式：只读对账（不推送）"
  local local_v public_v
  local_v="$(private_cli_version)"
  if ! public_v="$(public_cli_version)"; then
    echo "❌ 无法读取公开仓 nolotus/nolo 当前版本（无 push/读权限或网络不可达）"
    exit 1
  fi
  echo "   私有仓待投影 cli 版本: $local_v"
  echo "   公开仓当前 cli 版本:   ${public_v:-<unknown>}"
  if [ -z "$public_v" ]; then
    echo "❌ 公开仓 packages/cli/package.json 读取失败"
    exit 1
  fi
  if [ "$local_v" = "$public_v" ]; then
    echo "✅ 投影一致（consistent）：公开仓已是最新投影"
    exit 0
  fi
  echo "⚠️  投影落后（behind）：公开仓落后于私有仓待投影版本"
  exit 2
}

if [ "${1:-}" = "--check" ]; then
  check_mode
fi

echo "🔍 1/3 生成公开镜像（staging）..."
cd "$REPO_ROOT"
rm -rf "$STAGE_DIR"
if [ -n "${SYNC_PREPARE_CMD:-}" ]; then
  # 测试钩子：注入自定义 prepare 命令（离线测试用）
  eval "$SYNC_PREPARE_CMD"
else
  bun scripts/release/prepareNoloOpenSourceMirror.ts --out-dir "$STAGE_DIR"
fi

echo "📦 2/3 初始化 git 并以公开仓 main HEAD 为 parent 追加 commit..."
rm -rf "$MIRROR_DIR"
mkdir -p "$MIRROR_DIR"
cd "$MIRROR_DIR"
git init --quiet
git remote add origin "$PUBLIC_REPO" 2>/dev/null || true

# 拉取公开仓 main 当前 HEAD 作为 parent（append-only 的锚点）
git fetch --quiet origin "$PUBLIC_BRANCH"
git checkout -q -b "$PUBLIC_BRANCH" "origin/$PUBLIC_BRANCH"

# 用 staging 投影树替换工作区内容（保留 .git）
find . -mindepth 1 -maxdepth 1 ! -name '.git' -exec rm -rf {} +
cp -R "$STAGE_DIR"/. .

git add -A
RELEASE_TAGS="$(source_release_tags)"
if git diff --cached --quiet; then
  FILE_COUNT=$(git ls-files | wc -l | tr -d ' ')
  echo "   投影无变化（no-op）：公开仓 main 已包含相同的 $FILE_COUNT 个文件"
  echo "   Source-Commit: $SOURCE_COMMIT"
  echo "   Source-Release-Tag: $RELEASE_TAGS"
  echo "✅ 完成！无需创建 commit 或推送，公共仓库已是最新投影"
  exit 0
fi

COMMIT_MSG="chore: sync open-source public projection $(date -u +%Y-%m-%d)

Generated by syncNoloOpenSourceMirror.sh from bun-nolo.
Projection gate: 0 violations (PASS).

Source-Commit: $SOURCE_COMMIT
Source-Release-Tag: $RELEASE_TAGS"
git commit --quiet -m "$COMMIT_MSG"

FILE_COUNT=$(git ls-files | wc -l | tr -d ' ')
echo "   提交 $FILE_COUNT 个文件（parent=公开仓 main HEAD）"

echo "🚀 3/3 fast-forward 推送到 nolotus/nolo..."
push_with_retry() {
  if git push origin "$PUBLIC_BRANCH"; then
    return 0
  fi
  # 远端分叉：fetch --rebase 本地投影分支重试一次
  echo "   ⚠️ 远端分叉，fetch --rebase 重试一次..."
  git fetch --quiet origin "$PUBLIC_BRANCH"
  git rebase "origin/$PUBLIC_BRANCH"
  git push origin "$PUBLIC_BRANCH"
}
if ! push_with_retry; then
  echo "❌ 推送失败：公开仓 main 分叉且 rebase 后仍无法 fast-forward。"
  echo "   请人工检查 nolotus/nolo main 是否被非投影 commit 修改。"
  exit 1
fi

echo "✅ 完成！公共仓库已更新：https://github.com/nolotus/nolo"
echo "   CI 将自动触发：projection gate + build 验证"
