/**
 * Build an account-private Agent snapshot for explicit sync upload.
 *
 * Policy:
 * - Upload Agent fields only (no dialogs/messages/attachments).
 * - Never upload raw API keys, tokens, passwords, or credential material.
 * - A synced custom API key keeps only its validated `credentialRef`; the raw
 *   key remains encrypted in the owner-scoped server credential store.
 * - Preserve only provider OAuth `apiKeyRef` ids already used by runtime
 *   proxy routing (chatgpt / xai / antigravity). Uses pure
 *   `agent-runtime/serverProxyPolicy` — not a second provider registry;
 *   database must not import ai/app (cycle).
 * - Harmless `apiKeyHeader` names may be kept; secret-looking values strip.
 * - Local broker paths and machine-local binding details are dropped.
 */

import { isRecord } from "core/isRecord";
import { asOptionalFiniteNumber } from "core/optionalNumber";
import { asTrimmedLowercaseString } from "core/trimmedLowercaseString";
import { asTrimmedString } from "core/trimmedString";
import { createAgentKey } from "database/keys";
import { DataType } from "create/types";
import { isOAuthApiKeyRef } from "agent-runtime/serverProxyPolicy";

/** Field names that must never leave the device as raw secrets. */
const SECRET_FIELD_NAMES = new Set([
  "apiKey",
  "apikey",
  "API_KEY",
  "password",
  "passwd",
  "secret",
  "clientSecret",
  "client_secret",
  "accessToken",
  "access_token",
  "refreshToken",
  "refresh_token",
  "sessionToken",
  "session_token",
  "bearerToken",
  "bearer_token",
  "authorization",
  "authHeader",
  "auth_header",
  "privateKey",
  "private_key",
  "token",
  "credentials",
  "credential",
  "oauthToken",
  "oauth_token",
  "idToken",
  "id_token",
]);

/** Local-only / broker path material never uploaded. */
const LOCAL_ONLY_FIELDS = new Set([
  "credentialMigration",
  "localBrokerPath",
  "brokerPath",
  "credentialPath",
  "homeDir",
  "cwd",
  "workspacePath",
  "dialogIds",
  "dialogs",
  "messages",
  "messageIds",
  "attachments",
  "attachmentIds",
  "history",
  "chatHistory",
]);

const looksLikeRawSecret = (value: unknown): boolean => {
  if (typeof value !== "string") return false;
  const trimmed = value.trim();
  if (!trimmed) return false;
  // OpenAI-style API keys.
  if (/^sk-[A-Za-z0-9_-]{8,}$/.test(trimmed)) return true;
  // Explicit bearer material.
  if (/^Bearer\s+\S{16,}$/i.test(trimmed)) return true;
  // Device broker refs (api-key:…) are machine-local, not account OAuth ids.
  if (/^api-key:/i.test(trimmed)) return true;
  // Long opaque tokens without the separators common in dbKeys / refs.
  if (/^[A-Za-z0-9_]{40,}$/.test(trimmed)) return true;
  return false;
};

/** True when apiKeyRef is a known provider OAuth subscription id. */
export function isAccountSafeOAuthApiKeyRef(value: unknown): boolean {
  return isOAuthApiKeyRef(value);
}

/** Harmless HTTP header name for API keys (e.g. Authorization), not a secret. */
const isSafeApiKeyHeader = (value: unknown): boolean => {
  if (typeof value !== "string") return false;
  const trimmed = value.trim();
  if (!trimmed || looksLikeRawSecret(trimmed)) return false;
  // Header names are short tokens; reject anything that looks like material.
  if (trimmed.length > 64) return false;
  if (/\s/.test(trimmed)) return false;
  return /^[A-Za-z0-9-]+$/.test(trimmed);
};

const maybeKeepRefField = (
  key: string,
  value: unknown
): string | undefined => {
  if (key === "credentialRef") {
    // A synced custom API key needs a stable, non-secret lookup reference on
    // the account Agent. The key itself remains in the encrypted owner store.
    if (typeof value !== "string" || !/^api-key:[a-zA-Z0-9:_-]{1,128}$/.test(value.trim())) {
      return undefined;
    }
    return value.trim();
  }
  if (key === "apiKeyRef") {
    if (!isAccountSafeOAuthApiKeyRef(value)) return undefined;
    return asTrimmedLowercaseString(value);
  }
  if (key === "apiKeyHeader") {
    if (!isSafeApiKeyHeader(value)) return undefined;
    return (value as string).trim();
  }
  return undefined;
};

export type StripAgentForAccountSyncInput = {
  localAgent: Record<string, unknown>;
  accountUserId: string;
  /** Optional pre-allocated agent id; generated by caller when omitted. */
  agentId: string;
  now?: number;
};

export type AccountAgentSnapshot = Record<string, unknown> & {
  id: string;
  type: string;
  userId: string;
  dbKey: string;
  isPublic: false;
  createdAt: number;
  updatedAt: number;
};

/**
 * Produce a distinct account-private Agent record for write paths.
 * Does not mutate the local agent. Does not touch dialogs/messages.
 */
export function stripAgentForAccountSync(
  input: StripAgentForAccountSyncInput
): AccountAgentSnapshot {
  const accountUserId = asTrimmedString(input.accountUserId);
  if (!accountUserId || accountUserId === "local") {
    throw new Error(
      "stripAgentForAccountSync requires a non-local accountUserId"
    );
  }
  const agentId = asTrimmedString(input.agentId);
  if (!agentId) {
    throw new Error("stripAgentForAccountSync requires agentId");
  }

  const now = asOptionalFiniteNumber(input.now) ?? Date.now();
  const source = input.localAgent;
  const remoteDbKey = createAgentKey.private(accountUserId, agentId);

  const out: Record<string, unknown> = {};

  for (const [rawKey, value] of Object.entries(source)) {
    const key = rawKey;
    if (SECRET_FIELD_NAMES.has(key)) {
      continue;
    }
    if (LOCAL_ONLY_FIELDS.has(key)) {
      continue;
    }
    if (key === "apiKeyRef" || key === "apiKeyHeader") {
      const kept = maybeKeepRefField(key, value);
      if (kept !== undefined) out[key] = kept;
      continue;
    }
    // Drop identity / ownership fields; rewrite below.
    if (
      key === "id" ||
      key === "dbKey" ||
      key === "userId" ||
      key === "type" ||
      key === "isPublic" ||
      key === "spaceId" ||
      key === "serverOrigin" ||
      key === "authorityServer" ||
      key === "createdAt" ||
      key === "updatedAt" ||
      key === "dialogCount" ||
      key === "messageCount" ||
      key === "tokenCount"
    ) {
      continue;
    }
    // Runtime binding may embed machine/local owner paths — strip whole object
    // rather than risk uploading local broker/machine identity.
    if (key === "runtimeBinding") {
      continue;
    }
    if (value === undefined) continue;
    if (key === "credentialRef") {
      const isSyncedCustomApiKey =
        source.apiSource === "custom" && source.credentialSynced === true;
      if (isSyncedCustomApiKey) {
        const kept = maybeKeepRefField(key, value);
        if (kept !== undefined) out[key] = kept;
      }
      continue;
    }
    if (typeof value === "string" && looksLikeRawSecret(value)) {
      continue;
    }
    if (isRecord(value)) {
      out[key] = stripNestedSecrets(value);
      continue;
    }
    out[key] = value;
  }

  const snapshot: AccountAgentSnapshot = {
    ...out,
    id: agentId,
    type: DataType.AGENT,
    userId: accountUserId,
    dbKey: remoteDbKey,
    isPublic: false,
    // Fresh account agent: no dialog/message history uploaded in this slice.
    dialogCount: 0,
    messageCount: 0,
    tokenCount: 0,
    createdAt: now,
    updatedAt: now,
  };

  return snapshot;
}

function stripNestedSecrets(
  obj: Record<string, unknown>
): Record<string, unknown> {
  const next: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(obj)) {
    if (SECRET_FIELD_NAMES.has(key) || LOCAL_ONLY_FIELDS.has(key)) continue;
    if (key === "apiKeyRef" || key === "apiKeyHeader" || key === "credentialRef") {
      const kept = maybeKeepRefField(key, value);
      if (kept !== undefined) next[key] = kept;
      continue;
    }
    if (typeof value === "string" && looksLikeRawSecret(value)) continue;
    if (isRecord(value)) {
      next[key] = stripNestedSecrets(value);
      continue;
    }
    next[key] = value;
  }
  return next;
}

/** Test/assert helper: true when a payload still contains secret-bearing fields. */
export function agentSnapshotContainsSecrets(
  record: Record<string, unknown> | null | undefined
): boolean {
  if (!record || typeof record !== "object") return false;
  const walk = (value: unknown): boolean => {
    if (!value || typeof value !== "object") return false;
    if (Array.isArray(value)) return value.some(walk);
    for (const [key, child] of Object.entries(value as Record<string, unknown>)) {
      if (key === "credentialRef" && maybeKeepRefField(key, child) !== undefined) {
        continue;
      }
      if (SECRET_FIELD_NAMES.has(key)) {
        if (typeof child === "string" && child.trim()) return true;
        if (child != null && child !== "") return true;
      }
      if (typeof child === "string" && looksLikeRawSecret(child)) return true;
      if (walk(child)) return true;
    }
    return false;
  };
  return walk(record);
}
