import React from "react";
import {
  LuAlarmClock,
  LuArchive,
  LuAtom,
  LuAward,
  LuBadgeCheck,
  LuBanknote,
  LuBatteryCharging,
  LuBell,
  LuBluetooth,
  LuBlocks,
  LuBot,
  LuBook,
  LuBookmark,
  LuBox,
  LuBoxes,
  LuBrain,
  LuBriefcase,
  LuBug,
  LuCake,
  LuCalendar,
  LuCamera,
  LuCar,
  LuChartBar,
  LuChartLine,
  LuCircleUser,
  LuCircleDollarSign,
  LuCircleHelp,
  LuClipboardList,
  LuClock,
  LuCloudRain,
  LuCloudSun,
  LuCloud,
  LuCode,
  LuCoffee,
  LuCommand,
  LuCompass,
  LuConstruction,
  LuContact,
  LuCopy,
  LuCpu,
  LuCrown,
  LuDatabase,
  LuDiamond,
  LuDownload,
  LuDroplets,
  LuDumbbell,
  LuEarth,
  LuEraser,
  LuFileText,
  LuFileCode,
  LuFileArchive,
  LuFileImage,
  LuFileSpreadsheet,
  LuFileType,
  LuFilm,
  LuFingerprint,
  LuFlag,
  LuFlame,
  LuFlaskConical,
  LuFlower,
  LuFlower2,
  LuFolder,
  LuFolderKanban,
  LuGamepad2,
  LuGem,
  LuGift,
  LuGlobe,
  LuGraduationCap,
  LuHammer,
  LuHandshake,
  LuHardDrive,
  LuHeadphones,
  LuHeart,
  LuHospital,
  LuHouse,
  LuImage,
  LuKanban,
  LuKey,
  LuLayers,
  LuLayoutGrid,
  LuLeaf,
  LuLanguages,
  LuLaptop,
  LuLibrary,
  LuLightbulb,
  LuLink,
  LuListTodo,
  LuMail,
  LuMap,
  LuMapPin,
  LuMedal,
  LuMegaphone,
  LuMessageSquare,
  LuMic,
  LuMonitor,
  LuMousePointer2,
  LuMountain,
  LuMoon,
  LuMusic,
  LuNetwork,
  LuNewspaper,
  LuNotebook,
  LuPackage,
  LuPalette,
  LuPaperclip,
  LuPaintbrush,
  LuPenTool,
  LuPencil,
  LuPlane,
  LuPrinter,
  LuPuzzle,
  LuQrCode,
  LuRadar,
  LuReceipt,
  LuRecycle,
  LuRoute,
  LuScanLine,
  LuSchool,
  LuSearch,
  LuServer,
  LuSettings,
  LuShell,
  LuShip,
  LuShield,
  LuShoppingBag,
  LuSiren,
  LuSlidersHorizontal,
  LuSmile,
  LuSmartphone,
  LuSnowflake,
  LuSparkles,
  LuSprout,
  LuStar,
  LuStore,
  LuSun,
  LuSunrise,
  LuSunset,
  LuTable,
  LuTags,
  LuTarget,
  LuTelescope,
  LuTerminal,
  LuTicket,
  LuTimer,
  LuTrophy,
  LuTreePine,
  LuTrees,
  LuTruck,
  LuUmbrella,
  LuUsers,
  LuVegan,
  LuVideo,
  LuWallet,
  LuWifi,
  LuWrench,
  LuWheat,
  LuApple,
  LuBean,
  LuClover,
  LuWorkflow,
  LuZap,
} from "react-icons/lu";
import type { IconType } from "react-icons";
import type { ContentIcon as ContentIconValue } from "./types";
import "./contentIcon.css";

const LUCIDE_ICONS: Record<Extract<ContentIconValue, { kind: "lucide" }>["value"], IconType> = {
  "file-text": LuFileText,
  table: LuTable,
  "layout-grid": LuLayoutGrid,
  star: LuStar,
  book: LuBook,
  image: LuImage,
  folder: LuFolder,
  "folder-kanban": LuFolderKanban,
  kanban: LuKanban,
  layers: LuLayers,
  notebook: LuNotebook,
  "clipboard-list": LuClipboardList,
  briefcase: LuBriefcase,
  calendar: LuCalendar,
  clock: LuClock,
  "list-todo": LuListTodo,
  "chart-bar": LuChartBar,
  "chart-line": LuChartLine,
  database: LuDatabase,
  code: LuCode,
  "file-code": LuFileCode,
  terminal: LuTerminal,
  settings: LuSettings,
  wrench: LuWrench,
  "pen-tool": LuPenTool,
  palette: LuPalette,
  sparkles: LuSparkles,
  brain: LuBrain,
  bot: LuBot,
  "message-square": LuMessageSquare,
  users: LuUsers,
  globe: LuGlobe,
  link: LuLink,
  bookmark: LuBookmark,
  heart: LuHeart,
  flag: LuFlag,
  zap: LuZap,
  lightbulb: LuLightbulb,
  search: LuSearch,
  map: LuMap,
  "shopping-bag": LuShoppingBag,
  music: LuMusic,
  video: LuVideo,
  blocks: LuBlocks,
  flower: LuFlower,
  "flower-2": LuFlower2,
  leaf: LuLeaf,
  sprout: LuSprout,
  "tree-pine": LuTreePine,
  trees: LuTrees,
  clover: LuClover,
  vegan: LuVegan,
  bean: LuBean,
  wheat: LuWheat,
  apple: LuApple,
  sun: LuSun,
  "cloud-sun": LuCloudSun,
  "cloud-rain": LuCloudRain,
  droplets: LuDroplets,
  mountain: LuMountain,
  earth: LuEarth,
  shell: LuShell,
  archive: LuArchive,
  award: LuAward,
  "badge-check": LuBadgeCheck,
  bell: LuBell,
  box: LuBox,
  boxes: LuBoxes,
  cake: LuCake,
  camera: LuCamera,
  "circle-dollar-sign": LuCircleDollarSign,
  "circle-help": LuCircleHelp,
  coffee: LuCoffee,
  compass: LuCompass,
  cpu: LuCpu,
  crown: LuCrown,
  diamond: LuDiamond,
  dumbbell: LuDumbbell,
  "file-archive": LuFileArchive,
  "file-image": LuFileImage,
  "file-spreadsheet": LuFileSpreadsheet,
  "file-type": LuFileType,
  "flask-conical": LuFlaskConical,
  "gamepad-2": LuGamepad2,
  gift: LuGift,
  "graduation-cap": LuGraduationCap,
  hammer: LuHammer,
  handshake: LuHandshake,
  headphones: LuHeadphones,
  house: LuHouse,
  key: LuKey,
  languages: LuLanguages,
  laptop: LuLaptop,
  library: LuLibrary,
  mail: LuMail,
  megaphone: LuMegaphone,
  mic: LuMic,
  monitor: LuMonitor,
  moon: LuMoon,
  newspaper: LuNewspaper,
  package: LuPackage,
  paperclip: LuPaperclip,
  plane: LuPlane,
  puzzle: LuPuzzle,
  route: LuRoute,
  shield: LuShield,
  smile: LuSmile,
  tags: LuTags,
  target: LuTarget,
  telescope: LuTelescope,
  ticket: LuTicket,
  trophy: LuTrophy,
  wallet: LuWallet,
  workflow: LuWorkflow,
  "alarm-clock": LuAlarmClock,
  atom: LuAtom,
  banknote: LuBanknote,
  "battery-charging": LuBatteryCharging,
  bluetooth: LuBluetooth,
  bug: LuBug,
  car: LuCar,
  "circle-user": LuCircleUser,
  cloud: LuCloud,
  command: LuCommand,
  construction: LuConstruction,
  contact: LuContact,
  copy: LuCopy,
  download: LuDownload,
  eraser: LuEraser,
  film: LuFilm,
  fingerprint: LuFingerprint,
  flame: LuFlame,
  gem: LuGem,
  "hard-drive": LuHardDrive,
  hospital: LuHospital,
  "map-pin": LuMapPin,
  medal: LuMedal,
  "mouse-pointer-2": LuMousePointer2,
  network: LuNetwork,
  paintbrush: LuPaintbrush,
  pencil: LuPencil,
  printer: LuPrinter,
  "qr-code": LuQrCode,
  radar: LuRadar,
  receipt: LuReceipt,
  recycle: LuRecycle,
  "scan-line": LuScanLine,
  school: LuSchool,
  server: LuServer,
  ship: LuShip,
  siren: LuSiren,
  "sliders-horizontal": LuSlidersHorizontal,
  smartphone: LuSmartphone,
  snowflake: LuSnowflake,
  store: LuStore,
  sunrise: LuSunrise,
  sunset: LuSunset,
  timer: LuTimer,
  truck: LuTruck,
  umbrella: LuUmbrella,
  wifi: LuWifi,
};

export const isContentIcon = (value: unknown): value is ContentIconValue => {
  if (!value || typeof value !== "object") return false;
  const icon = value as Partial<ContentIconValue>;
  if (icon.kind === "emoji") {
    return typeof icon.value === "string" && icon.value.trim().length > 0;
  }
  if (icon.kind === "lucide") {
    return typeof icon.value === "string" && icon.value in LUCIDE_ICONS;
  }
  return false;
};

export const normalizeContentIcon = (value: unknown): ContentIconValue | null =>
  isContentIcon(value) ? value : null;

type ContentIconProps = {
  icon?: ContentIconValue | null;
  fallback: IconType;
  size?: number;
  className?: string;
};

export default function ContentIcon({
  icon,
  fallback: Fallback,
  size = 20,
  className,
}: ContentIconProps) {
  const normalizedIcon = normalizeContentIcon(icon);
  if (normalizedIcon?.kind === "emoji") {
    return (
      <span
        className={`content-icon content-icon--emoji${className ? ` ${className}` : ""}`}
        style={{ width: size, height: size, fontSize: Math.max(12, size - 2) }}
        aria-hidden="true"
      >
        {normalizedIcon.value}
      </span>
    );
  }

  const Icon =
    normalizedIcon?.kind === "lucide"
      ? LUCIDE_ICONS[normalizedIcon.value]
      : Fallback;
  return <Icon size={size} className={`content-icon${className ? ` ${className}` : ""}`} />;
}
