// 文件路径: packages/app/pages/HomeStyles.ts
import * as stylex from "@stylexjs/stylex";

/**
 * Home 页静态样式（自 Home.css 迁移至 StyleX）。
 *
 * 拆分约定与 agentCreateStylexEscapeHatch.css 相同：
 * - 本文件只放 stylex.create 能表达的元素级静态样式；
 * - 无法表达或属跨文件契约的规则留在 Home.css 逃生舱（每条注明保留原因），
 *   TSX 侧用 stylex.props(styles.x, "hook-class") 与 hook 类名并存。
 */
export const homeStyles = stylex.create({
  // 布局根（游客）。flexShrink: 0 不可省：显式 minHeight 会覆盖 flex 项的
  // 自动内容最小高度，若允许收缩，固定高的 MainLayout__main 会把本元素压成
  // 恰好一屏，内容溢出而 SiteFooter 落在首屏底部（视觉上悬在页面中间）。
  homeLayout: {
    minHeight: "100%",
    display: "flex",
    flexDirection: "column",
    flexGrow: 1,
    flexShrink: 0,
    flexBasis: "auto",
    backgroundColor: "var(--surfaceCanvas, var(--background))",
  },
  // 登录态变体：保持原 .home-layout--authed 的 flex: 1 1 0%（可收缩）。
  // 登录后首页不渲染 SiteFooter，压缩行为历史上无可见影响，按原样保留。
  homeLayoutAuthed: {
    minHeight: "100%",
    display: "flex",
    flexDirection: "column",
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: "0%",
  },
  homeMain: {
    maxWidth: "1080px",
    marginTop: 0,
    marginRight: "auto",
    marginBottom: 0,
    marginLeft: "auto",
    paddingTop: "clamp(12px, 1.5vh, 24px)",
    paddingRight: "clamp(16px, 2vw, 24px)",
    paddingBottom: "clamp(16px, 2.5vh, 32px)",
    paddingLeft: "clamp(16px, 2vw, 24px)",
    display: "flex",
    flexDirection: "column",
    rowGap: "clamp(12px, 1.5vh, 20px)",
    columnGap: "clamp(12px, 1.5vh, 20px)",
  },
  // 原 .home-layout--authed .home-main（后代选择器改为条件应用）。
  homeMainAuthed: {
    flexGrow: 1,
    width: "100%",
    boxSizing: "border-box",
    paddingBottom: "clamp(12px, 2vh, 24px)",
  },
  homeAuthedWidgetsSection: {
    width: "100%",
    maxWidth: "min(880px, var(--home-content-max-width))",
    marginTop: 0,
    marginRight: "auto",
    marginBottom: 0,
    marginLeft: "auto",
    paddingTop: "clamp(4px, 1vh, 12px)",
    paddingRight: 0,
    paddingBottom: "clamp(36px, 6vh, 64px)",
    paddingLeft: 0,
  },
  homeAuthedWidgetsHeader: {
    position: "relative",
    display: "flex",
    justifyContent: "flex-end",
    alignItems: "center",
    marginBottom: "clamp(4px, 0.8vh, 10px)",
    width: "100%",
  },
  homeEditBtn: {
    display: "flex",
    alignItems: "center",
    gap: "var(--space-1)",
    color: "var(--textSecondary)",
    textDecoration: "none",
    fontWeight: 500,
    fontSize: "var(--fontSize-xs, 12px)",
    paddingTop: 3,
    paddingRight: 12,
    paddingBottom: 3,
    paddingLeft: 12,
    borderRadius: "999px",
    backgroundColor: "var(--surfaceInteractive, var(--backgroundSecondary))",
    borderStyle: "solid",
    borderWidth: "1px",
    borderColor: "var(--borderMuted, var(--borderLight))",
    cursor: "pointer",
    opacity: 0.85,
    transitionProperty: "all",
    transitionDuration: "0.18s",
    transitionTimingFunction: "ease",
    ":hover": {
      opacity: 1,
      color: "var(--primary)",
      backgroundColor: "var(--surfaceInteractiveHover, var(--backgroundHover))",
      borderColor: "var(--primaryBorder, var(--primary))",
    },
  },
  homeEditBtnActive: {
    color: "var(--primary)",
    backgroundColor:
      "var(--primaryGhost, color-mix(in srgb, var(--primary) 10%, transparent))",
    borderColor: "var(--primary)",
  },
  homeWidgetsTip: {
    position: "absolute",
    top: "calc(100% + 8px)",
    right: 0,
    zIndex: 30,
    width: "min(320px, 82vw)",
    boxSizing: "border-box",
    backgroundColor: "var(--surfaceRaised, var(--surfaceCard))",
    borderStyle: "solid",
    borderWidth: "1px",
    borderColor: "var(--border)",
    borderRadius: "var(--radius-lg)",
    boxShadow: "0 8px 24px var(--shadowLight)",
    paddingTop: 10,
    paddingRight: 12,
    paddingBottom: 10,
    paddingLeft: 12,
  },
  // 气泡小箭头（原 .home-widgets-tip::before）。原为 background: inherit，
  // 等价于继承父级背景 var(--surfaceRaised, var(--surfaceCard))，此处直接用 token。
  homeWidgetsTipBefore: {
    "::before": {
      content: '""',
      position: "absolute",
      top: "-5px",
      right: "24px",
      width: "10px",
      height: "10px",
      backgroundColor: "var(--surfaceRaised, var(--surfaceCard))",
      borderLeftStyle: "solid",
      borderLeftWidth: "1px",
      borderLeftColor: "var(--border)",
      borderTopStyle: "solid",
      borderTopWidth: "1px",
      borderTopColor: "var(--border)",
      transform: "rotate(45deg)",
    },
  },
  homeWidgetsTipText: {
    marginTop: 0,
    marginRight: 0,
    marginBottom: "8px",
    marginLeft: 0,
    fontSize: "var(--fontSize-sm)",
    lineHeight: 1.5,
    color: "var(--text)",
  },
  homeWidgetsTipDone: {
    display: "inline-flex",
    alignItems: "center",
    paddingTop: 4,
    paddingRight: 14,
    paddingBottom: 4,
    paddingLeft: 14,
    borderRadius: "999px",
    borderStyle: "none",
    borderWidth: 0,
    backgroundColor: "var(--primary)",
    color: "#fff",
    fontSize: "var(--fontSize-sm)",
    cursor: "pointer",
    transitionProperty: "opacity",
    transitionDuration: "0.15s",
    ":hover": { opacity: 0.85 },
  },
  homeBottomChatShell: {
    position: "sticky",
    bottom: "clamp(12px, 2vh, 24px)",
    zIndex: 20,
    width: "100%",
    maxWidth: "var(--home-content-max-width)",
    marginTop: "auto",
    marginRight: "auto",
    marginLeft: "auto",
    pointerEvents: "none",
  },
  homePrimaryChat: {
    width: "100%",
    maxWidth: "var(--home-content-max-width)",
    marginTop: "clamp(8px, 1vw, 14px)",
    marginRight: "auto",
    marginBottom: 0,
    marginLeft: "auto",
    paddingTop: 0,
    paddingRight: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    backgroundColor: "transparent",
    borderStyle: "none",
    borderWidth: 0,
    boxShadow: "none",
  },
  // 原 .home-bottom-chat-shell .home-primary-chat（后代选择器改为条件应用）。
  homePrimaryChatInShell: {
    marginTop: 0,
    pointerEvents: "auto",
    order: 2,
  },
  homeContentSection: {
    opacity: 1,
    maxWidth: "var(--home-content-max-width)",
    marginTop: 0,
    marginRight: "auto",
    marginBottom: 0,
    marginLeft: "auto",
    width: "100%",
    paddingTop: "clamp(20px, 2vw, 28px)",
    paddingRight: 0,
    paddingBottom: "clamp(20px, 2vw, 28px)",
    paddingLeft: 0,
    borderStyle: "none",
    borderWidth: 0,
    backgroundColor: "transparent",
    boxShadow: "none",
    // 原 #ai-plaza-section 的 scroll-margin-top（锚点跳转留出顶部空间）。
    scrollMarginTop: "clamp(16px, 4vw, 32px)",
    "@media (max-width: 640px)": {
      paddingTop: "var(--space-2)",
      paddingBottom: "var(--space-2)",
    },
  },
  homePlazaBridge: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "var(--space-3)",
    marginTop: 0,
    marginRight: "auto",
    marginBottom: "var(--space-4)",
    marginLeft: "auto",
    maxWidth: "var(--home-content-max-width)",
  },
  homePlazaBridgeKicker: {
    fontSize: "0.75rem",
    fontWeight: 700,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: "var(--textMuted, var(--textSecondary))",
    whiteSpace: "nowrap",
  },
  homePlazaBridgeLine: {
    display: "block",
    width: "min(120px, 24vw)",
    height: "1px",
    backgroundImage:
      "linear-gradient(90deg, transparent, var(--borderMuted, var(--borderLight)), transparent)",
  },
  homeContentHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "var(--space-5)",
    gap: "12px",
    width: "100%",
    paddingBottom: "var(--space-3)",
    "@media (max-width: 640px)": {
      flexDirection: "column",
      alignItems: "flex-start",
      marginBottom: "var(--space-6)",
    },
  },
  homeViewAllLink: {
    display: "flex",
    alignItems: "center",
    gap: "var(--space-1)",
    color: "var(--textSecondary)",
    textDecoration: "none",
    fontWeight: 600,
    fontSize: "var(--fontSize-sm)",
    paddingTop: 8,
    paddingRight: 12,
    paddingBottom: 8,
    paddingLeft: 12,
    borderRadius: "999px",
    backgroundColor: "var(--surfaceInteractive, var(--backgroundSecondary))",
    borderStyle: "solid",
    borderWidth: "1px",
    borderColor: "var(--borderMuted, var(--borderLight))",
    transitionProperty: "background-color, color, border-color",
    transitionDuration: "0.2s",
    transitionTimingFunction: "ease",
    ":hover": {
      color: "var(--primary)",
      backgroundColor: "var(--surfaceInteractiveHover, var(--backgroundHover))",
      borderColor: "var(--primaryBorder, var(--primary))",
    },
    "@media (max-width: 640px)": {
      alignSelf: "flex-end",
      fontSize: "var(--fontSize-sm)",
    },
  },
  homeContentBody: {
    position: "relative",
    minHeight: "var(--home-pane-min-height)",
    width: "100%",
    paddingTop: 4,
  },
  tabLabelWithIcon: {
    display: "inline-flex",
    alignItems: "center",
    gap: "var(--space-2)",
    fontWeight: 600,
    letterSpacing: "-0.01em",
  },
  // HomePaneSkeleton 静态骨架（shimmer 动画仍在 Home.css 逃生舱）。
  homeSkeleton: {
    width: "100%",
    minHeight: "var(--home-pane-min-height)",
  },
  homeSkeletonGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(220px, 1fr))",
    gap: "var(--space-4)",
  },
  homeSkeletonCard: {
    borderStyle: "solid",
    borderWidth: "1px",
    borderColor: "var(--borderFaint, var(--borderLight))",
    borderRadius: "var(--radius-lg, 16px)",
    paddingTop: "var(--space-4)",
    paddingRight: "var(--space-4)",
    paddingBottom: "var(--space-4)",
    paddingLeft: "var(--space-4)",
    backgroundColor: "var(--surfaceRaised, var(--background))",
  },
  homeSkeletonHeader: {
    display: "flex",
    gap: "var(--space-3)",
    marginBottom: "var(--space-3)",
  },
  homeSkeletonAvatar: {
    width: "40px",
    height: "40px",
    borderRadius: "50%",
    flexShrink: 0,
  },
  homeSkeletonHeaderText: {
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: "0%",
    display: "flex",
    flexDirection: "column",
    gap: "var(--space-2)",
  },
  homeSkeletonBody: {
    display: "flex",
    flexDirection: "column",
    gap: "var(--space-2)",
  },
  homeSkeletonLine: {
    height: "10px",
    borderRadius: "999px",
  },
  homeSkeletonLineTitle: { width: "72%" },
  homeSkeletonLineSubtitle: { width: "48%" },
  homeSkeletonLineShort: { width: "56%" },
});
