import * as stylex from "@stylexjs/stylex";

/**
 * 课程笔记页（MediaLecturePage）样式。
 * 颜色/圆角/字号全部走主题 token（var(--xxx)），深色模式自动跟随；
 * 不改任何 DOM 结构、role、testid、文案，仅挂 className。
 */
export const mediaLectureStyles = stylex.create({
  page: {
    width: "100%",
    maxWidth: "960px",
    marginTop: 0,
    marginRight: "auto",
    marginBottom: 0,
    marginLeft: "auto",
    paddingTop: { default: "32px", "@media (max-width: 720px)": "20px" },
    paddingRight: { default: "24px", "@media (max-width: 720px)": "16px" },
    paddingBottom: { default: "72px", "@media (max-width: 720px)": "48px" },
    paddingLeft: { default: "24px", "@media (max-width: 720px)": "16px" },
    boxSizing: "border-box",
    display: "flex",
    flexDirection: "column",
    rowGap: "16px",
    color: "var(--text)",
    minWidth: 0,
  },
  title: {
    marginTop: 0,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    fontSize: "clamp(1.4rem, 2.2vw, 1.8rem)",
    fontWeight: 700,
    lineHeight: 1.35,
    color: "var(--textHeading, var(--text))",
    overflowWrap: "anywhere",
  },
  hint: {
    marginTop: 0,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    color: "var(--textSecondary)",
    fontSize: "var(--fontSize-sm)",
  },
  statusNotice: {
    marginTop: 0,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    paddingTop: "10px",
    paddingRight: "14px",
    paddingBottom: "10px",
    paddingLeft: "14px",
    borderRadius: "var(--radius-md)",
    border: "1px solid var(--borderSubtle)",
    backgroundColor: "var(--backgroundSecondary)",
    color: "var(--textSecondary)",
    fontSize: "var(--fontSize-sm)",
    lineHeight: 1.6,
  },
  statusAlert: {
    marginTop: 0,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    paddingTop: "10px",
    paddingRight: "14px",
    paddingBottom: "10px",
    paddingLeft: "14px",
    borderRadius: "var(--radius-md)",
    border: "1px solid var(--error)",
    backgroundColor: "var(--errorGhost)",
    color: "var(--error)",
    fontSize: "var(--fontSize-sm)",
    lineHeight: 1.6,
  },
  player: {
    display: "block",
    width: "100%",
    maxWidth: "100%",
    maxHeight: "420px",
    borderRadius: "var(--radius-lg)",
    boxSizing: "border-box",
  },
  tabBar: {
    display: "inline-flex",
    flexWrap: "wrap",
    alignSelf: "flex-start",
    maxWidth: "100%",
    columnGap: "4px",
    rowGap: "4px",
    padding: "4px",
    borderRadius: "var(--radius-lg)",
    border: "1px solid var(--border)",
    backgroundColor: "var(--backgroundSecondary)",
    boxSizing: "border-box",
  },
  tab: {
    appearance: "none",
    marginTop: 0,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    paddingTop: "6px",
    paddingRight: "14px",
    paddingBottom: "6px",
    paddingLeft: "14px",
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
    borderRadius: "var(--radius-md)",
    backgroundColor: "transparent",
    color: "var(--textSecondary)",
    fontSize: "var(--fontSize-sm)",
    fontWeight: 600,
    fontFamily: "inherit",
    cursor: "pointer",
    ":hover": { color: "var(--text)", backgroundColor: "var(--backgroundHover)" },
    ":focus-visible": { outline: "2px solid var(--primary)", outlineOffset: "2px" },
  },
  tabActive: {
    color: "var(--primary)",
    backgroundColor: "var(--background)",
    boxShadow: "0 1px 2px color-mix(in srgb, var(--text) 14%, transparent)",
  },
  panel: {
    display: "block",
    padding: "0 16px 14px",
    borderRadius: "var(--radius-lg)",
    border: "1px solid var(--border)",
    backgroundColor: "var(--background)",
    color: "var(--text)",
  },
  panelSummary: {
    paddingTop: "12px",
    paddingBottom: "12px",
    fontWeight: 600,
    fontSize: "var(--fontSize-base)",
    color: "var(--text)",
    cursor: "pointer",
  },
  fieldLabel: {
    display: "inline-flex",
    alignItems: "center",
    columnGap: "8px",
    marginTop: 0,
    marginRight: "16px",
    marginBottom: "10px",
    marginLeft: 0,
    color: "var(--textSecondary)",
    fontSize: "var(--fontSize-sm)",
  },
  select: {
    paddingTop: "5px",
    paddingRight: "10px",
    paddingBottom: "5px",
    paddingLeft: "10px",
    borderRadius: "var(--radius-md)",
    border: "1px solid var(--border)",
    backgroundColor: "var(--backgroundSecondary)",
    color: "var(--text)",
    fontSize: "var(--fontSize-sm)",
    fontFamily: "inherit",
  },
  input: {
    width: "120px",
    boxSizing: "border-box",
    paddingTop: "5px",
    paddingRight: "10px",
    paddingBottom: "5px",
    paddingLeft: "10px",
    borderRadius: "var(--radius-md)",
    border: "1px solid var(--border)",
    backgroundColor: "var(--backgroundSecondary)",
    color: "var(--text)",
    fontSize: "var(--fontSize-sm)",
    fontFamily: "inherit",
  },
  btn: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 0,
    marginRight: "8px",
    marginBottom: "8px",
    marginLeft: 0,
    paddingTop: "6px",
    paddingRight: "14px",
    paddingBottom: "6px",
    paddingLeft: "14px",
    borderRadius: "var(--radius-md)",
    border: "1px solid var(--border)",
    backgroundColor: "var(--backgroundSecondary)",
    color: "var(--text)",
    fontSize: "var(--fontSize-sm)",
    fontWeight: 500,
    fontFamily: "inherit",
    lineHeight: 1.4,
    cursor: "pointer",
    ":hover": { backgroundColor: "var(--backgroundHover)", borderColor: "var(--borderHover)" },
    ":focus-visible": { outline: "2px solid var(--primary)", outlineOffset: "2px" },
    ":disabled": { opacity: 0.5, cursor: "not-allowed" },
  },
  btnPrimary: {
    backgroundColor: "var(--primary)",
    borderColor: "var(--primary)",
    color: "var(--textOnPrimary, var(--primaryText, #fff))",
    ":hover": { backgroundColor: "var(--primary)", borderColor: "var(--primary)", opacity: 0.9 },
  },
  timeBtn: {
    display: "inline-flex",
    paddingTop: "2px",
    paddingRight: "6px",
    paddingBottom: "2px",
    paddingLeft: "6px",
    marginRight: "6px",
    marginBottom: 0,
    border: "none",
    borderRadius: "var(--radius-md)",
    backgroundColor: "transparent",
    color: "var(--primary)",
    fontVariantNumeric: "tabular-nums",
    fontSize: "var(--fontSize-sm)",
    fontWeight: 600,
    cursor: "pointer",
    ":hover": { backgroundColor: "var(--primaryGhost)", borderColor: "transparent" },
  },
  tableWrap: {
    width: "100%",
    overflowX: "auto",
    borderRadius: "var(--radius-lg)",
    border: "1px solid var(--border)",
    backgroundColor: "var(--background)",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    fontSize: "var(--fontSize-base)",
  },
  th: {
    paddingTop: "10px",
    paddingRight: "12px",
    paddingBottom: "10px",
    paddingLeft: "12px",
    textAlign: "left",
    fontSize: "var(--fontSize-sm)",
    fontWeight: 600,
    color: "var(--textSecondary)",
    borderBottom: "1px solid var(--border)",
    backgroundColor: "var(--backgroundSecondary)",
    whiteSpace: "nowrap",
  },
  td: {
    paddingTop: "10px",
    paddingRight: "12px",
    paddingBottom: "10px",
    paddingLeft: "12px",
    verticalAlign: "top",
    lineHeight: 1.7,
    color: "var(--text)",
    borderBottom: "1px solid var(--borderSubtle)",
    overflowWrap: "anywhere",
  },
  rowActive: {
    backgroundColor: "var(--accentSoft)",
    boxShadow: "inset 3px 0 0 var(--primary)",
  },
  translationItem: {
    marginTop: 0,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    paddingTop: "8px",
    paddingBottom: "8px",
    lineHeight: 1.8,
    color: "var(--text)",
    borderBottom: "1px solid var(--borderSubtle)",
  },
  list: {
    marginTop: 0,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    paddingLeft: "20px",
    lineHeight: 1.8,
    color: "var(--text)",
  },
  glossaryItem: {
    paddingTop: "8px",
    paddingBottom: "8px",
    borderBottom: "1px solid var(--borderSubtle)",
    lineHeight: 1.6,
  },
  dialog: {
    display: "flex",
    flexDirection: "column",
    rowGap: "10px",
    padding: "16px",
    borderRadius: "var(--radius-lg)",
    border: "1px solid var(--border)",
    backgroundColor: "var(--backgroundSecondary)",
    color: "var(--text)",
    boxSizing: "border-box",
  },
  dialogText: {
    marginTop: 0,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    lineHeight: 1.6,
    fontSize: "var(--fontSize-sm)",
  },
  actions: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    columnGap: "8px",
    rowGap: "8px",
  },
  formRow: {
    marginTop: 0,
    marginRight: 0,
    marginBottom: "12px",
    marginLeft: 0,
  },
});
