import * as stylex from "@stylexjs/stylex";

export const openAuditableSectionStyles = stylex.create({
  section: {
    width: "100%",
    maxWidth: "1120px",
    margin: "20px auto 72px",
    padding: "0 24px",
    boxSizing: "border-box",
  },
  shell: {
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "color-mix(in srgb, var(--primary, #1677ff) 22%, var(--border, #d0d7de))",
    borderRadius: "var(--radius-md)",
    padding: "24px",
    backgroundColor: "color-mix(in srgb, var(--primary, #1677ff) 4%, var(--background, #fff))",
    boxShadow: "0 12px 36px color-mix(in srgb, var(--primary, #1677ff) 7%, transparent)",
  },
  header: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 20,
    flexWrap: "wrap",
  },
  kicker: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    fontSize: 13,
    fontWeight: 700,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: "var(--primary, #1677ff)",
  },
  title: {
    margin: "8px 0 6px",
    fontSize: "clamp(1.35rem, 2vw, 1.8rem)",
    lineHeight: 1.25,
    color: "var(--text, inherit)",
  },
  description: {
    margin: 0,
    maxWidth: 720,
    lineHeight: 1.65,
    color: "var(--textSecondary, #57606a)",
  },
  links: {
    display: "flex",
    gap: 10,
    flexWrap: "wrap",
  },
  link: {
    display: "inline-flex",
    alignItems: "center",
    gap: 7,
    minHeight: 38,
    padding: "8px 12px",
    borderRadius: "var(--radius-xs)",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--border, #d0d7de)",
    textDecoration: "none",
    fontWeight: 600,
    color: "var(--text, inherit)",
    backgroundColor: "var(--background, #fff)",
  },
  proofs: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(210px, 1fr))",
    gap: 12,
    marginTop: 20,
  },
  proof: {
    display: "flex",
    alignItems: "flex-start",
    gap: 10,
    padding: "12px 14px",
    borderRadius: "var(--radius-xs)",
    backgroundColor: "color-mix(in srgb, var(--background, #fff) 82%, transparent)",
  },
  proofIcon: {
    flexShrink: 0,
    marginTop: 2,
    color: "var(--primary, #1677ff)",
  },
  proofTitle: {
    display: "block",
    fontSize: 14,
    fontWeight: 700,
    color: "var(--text, inherit)",
  },
  proofText: {
    display: "block",
    marginTop: 2,
    fontSize: 13,
    lineHeight: 1.5,
    color: "var(--textSecondary, #57606a)",
  },
  closing: {
    maxWidth: 880,
    margin: "64px auto 0",
    paddingTop: 56,
    borderTopWidth: 1,
    borderTopStyle: "solid",
    borderTopColor: "var(--border, #e5e7eb)",
    textAlign: "center",
  },
  closingLead: {
    margin: 0,
    color: "var(--textSecondary, #57606a)",
    fontSize: 16,
    lineHeight: 1.7,
  },
  closingLines: {
    display: "flex",
    justifyContent: "center",
    flexWrap: "wrap",
    gap: "8px 22px",
    margin: "22px 0 0",
    color: "var(--text, inherit)",
    fontSize: "clamp(1.55rem, 3.4vw, 2.55rem)",
    fontWeight: 700,
    lineHeight: 1.18,
    letterSpacing: "-0.035em",
  },
  closingEnd: {
    display: "block",
    marginTop: 14,
    color: "var(--primary, #1677ff)",
    fontSize: "clamp(1.7rem, 3.8vw, 2.8rem)",
    fontWeight: 700,
    letterSpacing: "-0.04em",
  },
  closingActions: {
    display: "flex",
    justifyContent: "center",
    gap: 12,
    marginTop: 30,
    flexWrap: "wrap",
  },
  primaryAction: {
    minHeight: 46,
    padding: "0 21px",
    borderRadius: "var(--radius-xs)",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    textDecoration: "none",
    fontWeight: 600,
    color: "#fff",
    backgroundColor: "var(--primary, #1677ff)",
    boxShadow: "0 8px 24px color-mix(in srgb, var(--primary, #1677ff) 18%, transparent)",
  },
  secondaryAction: {
    minHeight: 46,
    padding: "0 21px",
    borderRadius: "var(--radius-xs)",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    textDecoration: "none",
    fontWeight: 600,
    color: "var(--text, inherit)",
    backgroundColor: "var(--background, #fff)",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "color-mix(in srgb, var(--primary, #1677ff) 20%, var(--border, #d0d7de))",
  },
});
