// scripts/dev/routeStyles.js
// 作用：路由级样式（public/route-styles/*.css）的唯一权威来源。
// esBuild.js 一次性构建和 esDev.js watch 重建都复用这里的数据与生成逻辑，
// 避免 dev watch 下路由样式需要手动重新执行 one-shot build。

import { access, mkdir, readFile, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import { getRouteStyleTransformOptions } from "./webBuildPolicy.js";

const require = createRequire(import.meta.url);
const esbuild = require("esbuild");
const routeStyleSourceCache = new Map();

/**
 * 路由级样式源文件 → 输出文件名的映射（唯一权威清单）。
 * 每一项为 [源文件路径 | 源文件路径数组, 输出文件名]。
 * 不要在 esBuild.js / esDev.js 里复制这份清单。
 */
export const ROUTE_STYLE_FILES = [
  ["packages/render/table.css", "table.css"],
  ["packages/app/settings/web/settings.css", "settings.css"],
  [
    [
      "packages/app/pages/home-motion.css",
      "packages/app/pages/WelcomeSection.css",
      "packages/app/pages/WelcomeSection.hero.css",
      "packages/app/pages/WelcomeSection.orchestration.css",
      "packages/app/pages/Home.css",
    ],
    "home.css",
  ],
  [
    [
      "packages/app/pages/ShareImportPage.css",
      "packages/chat/messages/web/MessageLayout.css",
      "packages/app/pages/share/DocImportView.css",
      "packages/app/pages/share/ImportBar.css",
    ],
    "share.css",
  ],
  [
    [
      "packages/ai/agent/web/AgentForm.css",
      "packages/ai/agent/web/BasicInfoTab.css",
      "packages/ai/agent/web/ReferencesTab.css",
      "packages/ai/agent/web/ReferencesSelector.css",
      "packages/ai/agent/web/ToolsTab.css",
      "packages/ai/agent/web/PublishSettingsTab.css",
      "packages/ai/agent/web/GreetingMenuEditor.css",
      "packages/ai/agent/web/WhitelistInput.css",
      "packages/create/version/VersionHistoryPanel.css",
    ],
    "agent-form.css",
  ],
];

const GENERATED_BANNER_PREFIX = "/* GENERATED by scripts/dev/routeStyles.js";

/**
 * 全部输出文件名（派生自 ROUTE_STYLE_FILES，保持单一权威清单）。
 * 部署后探测、引用契约测试都复用这份名单，不要在别处复制。
 */
export const ROUTE_STYLE_OUTPUT_NAMES = Object.freeze(
  ROUTE_STYLE_FILES.map(([, fileName]) => fileName)
);

/**
 * 校验输出目录里每个路由级样式产物：存在、非空、且带 GENERATED banner。
 * 任何一个不满足都抛错，避免「构建成功但产物缺失/陈旧」被静默发布。
 *
 * @param {object} [options]
 * @param {Array} [options.files] 与 copyRouteStyles 相同的清单，便于测试注入。
 * @param {string} [options.outputDir] 输出目录。
 * @returns {Promise<void>}
 */
export const verifyRouteStyles = async ({
  files = ROUTE_STYLE_FILES,
  outputDir = "public/route-styles",
} = {}) => {
  await Promise.all(
    files.map(async ([, fileName]) => {
      const outputPath = `${outputDir}/${fileName}`;
      let content;
      try {
        content = await readFile(outputPath, "utf8");
      } catch (error) {
        throw new Error(
          `route-style 产物缺失: ${outputPath}。请先运行 bun run build（由 scripts/dev/routeStyles.js 生成）。`,
          { cause: error }
        );
      }
      if (content.length === 0) {
        throw new Error(`route-style 产物为空: ${outputPath}。请重新运行 bun run build。`);
      }
      if (!content.startsWith(GENERATED_BANNER_PREFIX)) {
        throw new Error(
          `route-style 产物缺少 GENERATED banner: ${outputPath}。该文件可能是手写/陈旧产物，请删除后重新运行 bun run build。`
        );
      }
    })
  );
};

/**
 * 读取并合并一组 CSS 源文件，用与构建相同的 transform 选项处理后写入输出目录。
 *
 * @param {object} [options]
 * @param {Array} [options.files] 覆盖默认 ROUTE_STYLE_FILES，便于测试注入临时源/输出。
 * @param {string} [options.outputDir] 覆盖默认输出目录，便于测试隔离。
 * @param {object} [options.env] 透传给 getRouteStyleTransformOptions 的环境变量。
 * @param {boolean} [options.skipUnchanged] dev watch 可跳过内容未变化的 transform/write。
 * @returns {Promise<void>}
 */
export const copyRouteStyles = async ({
  files = ROUTE_STYLE_FILES,
  outputDir = "public/route-styles",
  env,
  skipUnchanged = false,
} = {}) => {
  await mkdir(outputDir, { recursive: true });
  await Promise.all(
    files.map(async ([sources, fileName]) => {
      const sourceList = Array.isArray(sources) ? sources : [sources];
      const sourceCss = (
        await Promise.all(sourceList.map((source) => readFile(source, "utf8")))
      ).join("\n");
      const outputPath = `${outputDir}/${fileName}`;
      const outputExists =
        skipUnchanged &&
        (await access(outputPath).then(
          () => true,
          () => false
        ));
      if (
        skipUnchanged &&
        outputExists &&
        routeStyleSourceCache.get(outputPath) === sourceCss
      ) {
        return;
      }
      const result = await esbuild.transform(
        sourceCss,
        getRouteStyleTransformOptions({ env })
      );
      // Banner after transform: legalComments:"none" (and minify) strip comments.
      const banner = `${GENERATED_BANNER_PREFIX} from ${sourceList.join(", ")} — do not edit. */\n`;
      await writeFile(outputPath, banner + result.code);
      routeStyleSourceCache.set(outputPath, sourceCss);
    })
  );
  // 自检：写入完成后立即校验全部产物，构建/部署链上游立即失败而不是运行时才 404。
  await verifyRouteStyles({ files, outputDir });
};
